---
lang: de
title: "itc-ToolBox: Codes erzeugen"
---

Für die Erstellung von Logins sind Benutzernamen erforderlich. Außerdem können Kennworte und Codes als Teil des Login-Prozesses vorgesehen werden. Für die Vergabe dieser Codes stellt das IQB einige Anforderungen:

* Die Codes müssen eindeutig sein: Kein Login-Benutzername darf doppelt vorkommen.
* Die Zeichen müssen gut merkbar sein, damit bei der Übertragung vom Zettel in den Computer kein Fehler passiert.
* Die Tasten sollen auf der Computer-Tastatur gut findbar sein. Es sollte zur Eingabe nur eine Taste nötig sein. Großbuchstaben und die meisten Sonderzeichen sind also ungünstig.
* Die Zeichen müssen gut lesbar sein: Optisch sehr ähnliche Zeichen wie "n" und "m" oder "1" und "l" sind zu vermeiden.
* Die Codes müssen gut sprechbar und akustisch verständlich sein: Sollte z. B. die Testleiterin einem Schüler den Code ansagen, darf es keine Fehler geben.
* Es sollte keine Gefahr bestehen, dass durch nicht erkannte Zeichenkodierung von Dateien Probleme mit Sonderzeichen (Umlaute!) auftreten.

Die Funktion **Codes-Xlsx** erzeugt eine Excel-Tabelle mit Codes, die diese Regeln einhalten: Zweistellige, dreistellige, vierstellige und fünfstellige Codes. Das IQB verwendet eine Auswahl aus Kleinbuchstaben und Ziffern - keine Sonderzeichen und Umlaute. Kleinbuchstaben wechseln sich dabei mit Ziffern ab. Jeder Code kommt in der Tabelle jeweils nur einmal vor.

Nach der Entnahme bzw. dem "Benutzen" eines Codes sollte man diesen Code in der Tabelle farblich markieren, damit nicht versehentlich Codes doppelt vergeben werden.

::: {.callout-caution}
## Achtung Eindeutigkeit

Das Testcenter erlaubt es nicht, dass auf einem Server ein Benutzername doppelt vorkommt. Bitte rechnen Sie daher damit, dass das Hochladen einer Testtaker-Xlm scheitert, weil ein Login-Code in einem anderen Arbeitsbereich vergeben wurde. Sie erhalten einen entsprechenden Hinweis und tauschen dann diesen Code aus.
:::
