---
lang: de
title: "Endgeräte"
---

## Allgemein

Hardware und Betriebssystem spielen eine ehr untergeordnete Rolle. Da es sich um eine Webanwendung handelt, ist vielmehr der verwendete Browser und die Browserversion entscheidend. Darüber hinaus gibt es weitere Faktoren, die entscheidend sein können. Interessant könnte bspw. die Frage sein, welche Bildschirmgrößen mit welchen Auflösungen zum Einsatz kommen werden. Die Aufgabeninhalte verhalten sich zwar responsive, dennoch kann es sinnvoll sein, Aufgaben bzgl. der verwendeten  Bildschirme zu optimieren.

Auch die Frage ob Tastaturen zum Einsatz kommen werden, kann hilfreich sein. Kommen keine Tastaturen zum Einsatz und muss während der Durchführung mit den systemeigene Tastaturen (bspw. iPad) gearbeitet werden, kann auch dies einen Einfluss auf die Aufgabengestaltung haben und sollte den Aufgabenentwickler\*innen wenn möglich frühzeitig bekannt sein.

Werden in den Aufgaben Videos oder Audios verwendet, muss zuvor geklärt werden, ob Kopfhörer zur Verfügung stehen und wie diese an die verwendeten Endgeräte angeschlossen werden können. Je nach Studienumgebung kann es sinnvoll sein, Kopfhörer mit Geräuschunterdrückung zu verwenden.

Weitere Themen in diesem Kapitel:

* [Probleme mit Endgeräte](problems/index.qmd)
* [Kiosk-Mode](../devices/kiosk/index.qmd): Es kann gewünscht sein, die Funktionalitäten einzelner Geräte einzuschränken. Alle Geräte können dafür in einen so genannten Kiosk-Mode geschaltet werden. Es kann auch ein spezieller Browser verwendet werden.