---
lang: de
title: "Verbundelement Tabelle"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

## Tabelle

Der „Verbund: Tabelle“ hilft Ihnen beim Erstellen von Aufgaben mit Tabellen.

## Beispiel:
 
Nachdem Sie auf das (Verbund-)Element „Tabelle“ geklickt haben, wird automatisch eine Tabelle mit jeweils zwei Spalten und Zeilen generiert. Im rechten Reiter „Eigenschaften“ können Sie vielfältige Einstellungen im Tabellenelement („toolbox.table“) vornehmen. 

## Tabellen Eigenschaften

Neben der Anpassung der ID (z. B.: „table_1“) können Sie mit einem Klick auf den „Elemente anpassen“-Knopf in einzelne Tabellenzellen Elemente aus dem Editor einfügen. 

::: {.callout-note}
Das sich öffnende Menü für die Auswahl der Tabellenelemente können Sie auch über einen Doppelklick auf die Tabelle öffnen. 
:::
 
Nachdem Sie „Elemente anpassen“ ausgewählt haben, öffnen sich die Tabellenelemente. Hier können Sie durch Klicken auf Plus das jeweilige Element anpassen. Sie können zwischen den Elementen Text, Eingabefeld, Kontrollkästchen, Ablegeliste, Bild und Audio wählen. Das gewünschte Element wird in die Tabelle eingefügt. Es lässt sich ein Element pro Tabellenzelle einfügen.

Jedes angeklickte Element, das in eine Tabellenzelle eingefügt wurde, können Sie im rechten Reiter „Eigenschaften“ separat editieren.
 
Zudem können Sie die Anzahl der Zeilen und Spalten sowie deren Anteile oder Bildpunkte anpassen. Ob Anteile oder Bildpunkte genutzt werden, entscheiden Sie über einen Klick auf das Wort.
 
Wenn Sie Außenkanten für die Tabelle einstellen möchten, setzen Sie das Häkchen bei „Tabellenränder zeichnen“.
 
Darüber hinaus können Sie mit der Maximalbreite einstellen, wie breit (in Pixeln) die Tabelle maximal sein soll. Dies kann nützlich sein, wenn die Eintragungen oder Elemente in den einzelnen Tabellenzellen sehr kurz sind. Die Breite der Tabelle ist automatisch bereits durch die Seitenbreite begrenzt.

Eine Maximalbreite können Sie einstellen, indem Sie ein Häkchen bei „Maximalbreite setzen“ setzten und anschließend die Maximalbreite eintragen.

::: {.callout-tip}
Möchten Sie die Eigenschaften der Tabelle später anpassen, kann ein gezielter Klick auf die Tabelle an sich (z. B. um es anzupassen) schwierig sein. Mit einem Klick auf den ersten pinken Knopf am Abschnitt („Elementliste“) können Sie gezielter die Tabelle anhand der Tabellen-ID auswählen. 
:::

## Elemente editieren

Sie können die Elemente innerhalb der Tabelle einfach anklicken, um sie zu bearbeiten.

Textelemente können wie [hier](../Medienelemente/Text/index.qmd) beschrieben bearbeitet werden.

Eingabefelder können wie [hier](../Antwortfelder_Assistent/index.qmd) beschrieben bearbeitet werden.

Mit Kontrollkästchen können Felder in der Tabelle angekreuzt werden.
 
Mit Ablegelisten können Sie Zuordnungsaufgaben in Tabellen anlegen. Genau wie bei den Eingabefeldern können Sie auch hier eine feste Breite einstellen. Zu den Einstellungsmöglichkeiten von Ablegelisten siehe [Ablegeliste](../DaD/DaD_Assistent_Zuordnung/index.qmd).
 
Bildelemente können wie [hier](../Medienelemente/Bild/index.qmd) beschrieben bearbeitet werden.

Audioelemente können wie [hier](../Medienelemente/Audio/index.qmd) beschrieben bearbeitet werden.