---
lang: de
title: "Endgeräte"
---

Jedes Endgerät weißt spezifische Eigenschaften auf. Diese können unter bestimmten Bedingungen zu Problemen bei der Testdurchführung führen. In diesem Kapitel soll auf solche Gerätespezifischen Probleme und Eigenschaften hingewiesen werden.

## Allgemein

Hardware und Betriebssystem spielen eine ehr untergeordnete Rolle. Da es sich um eine Webanwendung handelt, müssen die Endgeräte über eine Internetanbindung verfügen. Durchaus interessant könnte die Frage sein, welche Bildschirmgrößen mit welchen Auflösungen zum Einsatz kommen werden. Die Aufgabeninhalte verhalten sich zwar dynamisch (responsive), dennoch kann es sinnvoll sein Aufgaben bzgl. der Darstellung zu optimieren. Kommen größtenteils kleinere Tablets zum Einsatz, sind bspw. Aufgaben bestehend aus zwei Seiten nur noch bedingt lesbar. Die Frage nach den verwendeten Endgeräten sollte also nicht erst kurz vor der eigentlichen Studiendurchführung gestellt werden, sondern wenn möglich bereits in der Aufgabenentwurfsphase.

Es kann auch günstig sein in Erfahrung zu bringen, ob Tastaturen zum Einsatz kommen werden. Kommen keine Tastaturen zum Einsatz und muss während der Durchführung mit den systemeigene Tastaturen (bspw. iPad) gearbeitet werden, kann auch dies einen Einfluss auf die Aufgabengestaltung haben und sollte den Aufgabenentwickler\*innen wenn möglich bekannt sein.

Werden in den Aufgaben Videos oder Audios verwendet, muss zuvor geklärt werden, ob Kopfhörer zur Verfügung stehen und wie diese an die verwendeten Endgeräte angeschlossen werden können. Je nach Studienumgebung kann es sinnvoll sein, Kopfhörer mit Geräuschunterdrückung zu verwenden.

## Endgeräte

* [iPad](/Testcenter/test-run/preparation/devices/ipad.qmd)