---
lang: de
title: "Häufig gestellten Fragen"
---

### Nach erfolgreicher Anmeldung ist kein Startbild mit den Testheften zu sehen

Eventuell besteht keine Internetverbindung. Es sollten entsprechende Routinen zur Fehlerbehebung beginnen (lose Kabel etc.).

### Es wird für die Anmeldung kein Testheft gefunden

Zugangsdaten prüfen. In der XML zur Studien-Definition prüfen, ob dem Zugang ein entsprechendes Testheft zugewiesen ist und ob dieses Testheft im Arbeitsreich existiert.

### Schalter Testheft ist inaktiv

Dies kann daraufhin deuten, dass das Testheft gesperrt ist. Je nach Konfiguration in der XML zur Testheft-Definition kann es sein, dass die Testhefte nach Beendigung der Testung gesperrt werden. Ein Testheft kann eventuell auch über einen eingesetzen Gruppenmonitor von der Testleitung gesperrt wurden sein. In diesem Fall kann die Sperrung mit dem Gruppenmonitor auch wieder aufgehoben werden.

### Aufgabeninhalte werden nicht präsentiert

Werden die Inhalte erst während der Durchführung geladen (Konfiguration zum Ladenverhalten sind in der XML zur Testheft-Definition festzulegen. Hier gibt es zwei Arten: LAZY und EAGER) kann es ein, dass Inhalte (Videos, Audios) noch geladen werden und die Testperson nicht sofort etwas sieht. Eventuell kann hier auch das Neuladen einer Seite hilfreich sein. Falls ein Gruppenmonitor zum Einsatz kommt, könnte dieser verwendet werden, um die Testperson noch einmal an den Anfang eines Block zu leiten und somit das Neuladen einer Aufgabe zu erzwingen.

::: {.callout-tip}
Sollten technische Probleme mit dem Computer auftreten (z. B. Audio-Buchse defekt), dann kann jederzeit der Browser geschlossen und der Test auf einem anderen Computer neu gestartet werden. Die schon gegebenen Antworten werden geladen und der Test kann fortgesetzt werden.
:::