---
lang: de
title: "Anforderungen"
---

# Systemanforderung

::: {.callout-important}
Werden die Systemanforderungen nicht erfüllt, ist eine Studien nicht durchführbar.
:::

## Browser

Darstellung und Verhalten einer Studie sind maßgeblich vom verwendeten Browser abhängig. Es gibt immer wieder die Diskussion darüber, ob bzw. in welchem Maße ältere Browser bzw. Browserversionen unterstützt werden sollen. Hier wird argumentiert, dass Schulen bzw. deren Träger oft nicht in der Lage seien, die Verwendung aktueller Browser sicherzustellen. Aus dieser Realität ergebe sich, dass die Programmierungen für TBA stets ein Maximum an Abdeckung auch für alte Browser leisten müssten.

Das IQB folgt hier jedoch den Anforderungen an die Datensicherheit, so wie es z. B. das [Bundesamt für Sicherheit in der Informationstechnik](https://www.bsi.bund.de/) formuliert:

> "Der Internet-Browser ist die zentrale Komponente für die Nutzung von Online-Angeboten und stellt somit eins der beliebtesten Ziele für Cyber-Angriffe dar. Hieraus ergibt sich ein besonders hohes Gefahrenpotenzial." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/Der-Browser/der-browser_node.html)

> "Installieren Sie alle Aktualisierungen sofort oder zeitnah nach ihrer Veröffentlichung, sowohl die für Ihren Browser, als auch für alle Erweiterungen und natürlich Ihr Betriebssystem. Verwenden Sie stets die neuste Version Ihres Browsers." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/updates-browser-open-source-software_node.html)

Das IQB unterstützt daher nur die jeweils letzten beiden Hauptversionen eines Browsers bzw. die Versionen der letzten 12 Monate. 

**Stand April 2024:**

* Firefox: 125 und 124
* Chrome: 123 und 122
* Edge: 124 und 123
* Safari: 17 und 16

Neu veröffentliche Browserversionen können unter Umständen Änderungen enthalten, die zu einem anderen Verhalten der Anwendung führen. Das IQB ist daher bemüht die Anwendung zeitnah in Verbindung mit Neuerscheinungen zu testen, kann dies aber nicht in jedem Fall gewährleisten, da die Vielzahl an möglichen neuen Browserversionen (Safari, Edge, Chrome, Firefox) recht herausfordernd ist. Sollten bereits neuere Versionen, als die hier genannten Versionen zum Einsatz kommen, empfiehlt sich eine Voransicht vor der Studiendurchführung. Hierfür bietet das Testcenter spezielle Modi der Studiendurchführung an, wie bspw. einen Review-Mode. Für einzelne Aufgaben zur Ansicht kann auch der **System-Check** verwendet werden. 

Ist von einem fehlerhaften Verhalten der Anwendung in Verbindung mit neueren Browserversionen auszugehen, kann eine Meldung an das Entwicklerteam erfolgen.

::: {.callout-important}
Es gibt abenteuerliche Erweiterungen für Browser (Plugins), die mehr Sicherheit, bessere Performance, weniger Werbung, mehr Privatsphäre usw. versprechen. Oft greifen diese Erweiterungen aber massiv in die Kommunikation des Browsers mit dem Server ein und verfälschen Daten. Bei Problemen sollte man also diese Add-Ons usw. zumindest zeitweise deaktivieren.
:::

::: {.callout-tip}
Um die Browserversionen zu überprüfen kann im Vorfeld ein System-Check durchgeführt werden.
:::

## Internetanbindung

Ist die Anbindung zu schlecht, kann im schlimmsten Fall die Studie im örtlichen Umfeld nicht durchgeführt werden. Leider kann an dieser Stelle keine generelle Aussage getroffen werden, ab welchen Werten eine Studie gesichert durchgeführt werden kann. Es ist aber möglich eine Abschätzung vorzunehmen:

1. Ermittlung der Größe des größten Testheftes: Im Testcenter wird unter dem Reiter: **Dateien** des Arbeitsbereiches eine Spalte "Größe" angezeigt. Diese Größe ist bei allen Dateien die tatsächliche Größe der Datei. Eine Ausnahme stellen die Testtaker-Dateien dar. Hier wird die Summe aller Dateien angezeigt, die für dieses Testheft geladen werden müssen (Booklet-XML, Unit-XML, Unit-VOUD, Player-HTML).
2. Festlegung der maximalen Zeit in Sekunden, nach der dieses Booklet geladen sein soll.
3. Die Formel **Testheft * 8 / Ladezeit** ergibt den Mindestwert für den Download in MBit/s.

Diese Abschätzung ist einigermaßen verlässlich, weil die Ermittlung der Download-Geschwindigkeit das Ladeverhalten des Testcenters nachbildet. Die Pakete werden beispielsweise nacheinander geladen und nicht parallel.

::: {.callout-tip}
Ist die Internetanbindung nicht ausreichend, kann das Testcenter auch offline betrieben werden. Hierfür wird das Testcenter auf einem PC installiert und die entsprechenden Endgeräte werden mit diesem verbunden. Der PC fungiert dann als Server. 
:::

## IT Sicherheitsstrukturen

Manche IT-Sicherheitskonzepte in den Einrichtungen können die Studiendurchführung stören oder gänzlich unmöglich machen. Daher ist es wichtig zuvor die Erreichbarkeit des Testcenters aus dem Netz der Einrichtung heraus zu prüfen. 

## Lastverhalten Testcenter Server

Entscheidend für die Durchführbarkeit einer Studie ist die Belastbarkeit des Servers auf dem das Testcenter läuft. Das Lastverhalten kann mit einem Lasttest ermittelt werden. Entscheidend ist hierbei bereits vor Studienstart die Anzahl der Teilnehmer\*innen zu kennen. Mehr dazu ist dem Kapitel: **Installation / Lastverhalten** zu entnehmen.
---

# Studienanforderung

Im Gegensatz zu den Systemanforderungen, handelt sich bei den Studienanforderungen um individuelle Anforderungen. Hier kann das IQB nur Empfehlung aus dem Praxisalltag geben und einige entscheidende Punkte nennen:

## Audiovisuelle Medien

Um auch bei schlechter Internetanbindung eine Studie durchführen zu können, sollten die Testheftgrößen so klein wie möglich gehalten werden. Die Testheftgröße hängt maßgeblich vom Einsatz audiovisueller Medien ab. Wenn nicht zwingend und auch mit anderen Aufgabenelementen darstellbar, sollten audiovisuelle Medien nur wenig eingesetzt werden. Da wo sie zum Einsatz kommen, muss auf die richtige Komprimierung geachtet werden. Damit audiovisuelle Medien während der Studiendurchführung gesichert funktionieren, sind außerdem die nachfolgenden Einstellungen entscheidend.

#### Audio

Audios mit geringem Anspruch an die Qualität (nur Sprache):

* Kompression: MP3
* Kanal: Stereo
* Abtastrate: 24000 Hz
* Bitraten Modus: Konstant
* Bitrate: 64kbps 

Audios mit höherem Anspruch an die Qualität (Musik enthalten):

* Kompression: MP3
* Kanal: Stereo
* Abtastrate: 44100 Hz
* Bitraten Modus: Konstant
* Bitrate: 96kbps 

#### Video

* Kompression: h.264 (MPEG-4 AVC)
* Kanal: Stereo

## Endgeräte

Hardware und Betriebssystem spielen eine ehr untergeordnete Rolle. Da es sich um eine Webanwendung handelt, müssen die Endgeräte über eine Internetanbindung verfügen. Durchaus interessant könnte die Frage sein, welche Bildschirmgrößen mit welchen Auflösungen zum Einsatz kommen werden. Die Aufgabeninhalte verhalten sich zwar dynamisch (responsive), dennoch kann es sinnvoll sein Aufgaben bzgl. der Darstellung zu optimieren. Kommen größtenteils kleinere Tablets zum Einsatz, sind bspw. Aufgaben bestehend aus zwei Seiten nur noch bedingt lesbar. Die Frage nach den verwendeten Endgeräten sollte also nicht erst kurz vor der eigentlichen Studiendurchführung gestellt werden, sondern wenn möglich bereits in der Aufgabenentwurfsphase.

Es kann auch günstig sein in Erfahrung zu bringen, ob Tastaturen zum Einsatz kommen werden. Kommen keine Tastaturen zum Einsatz und muss während der Durchführung mit den systemeigene Tastaturen (bspw. iPad) gearbeitet werden, kann auch dies einen Einfluss auf die Aufgabengestaltung haben und sollte den Aufgabenentwickler\*innen wenn möglich bekannt sein.

Werden in den Aufgaben Videos oder Audios verwendet, muss zuvor geklärt werden, ob Kopfhörer zur Verfügung stehen und wie diese an die verwendeten Endgeräte angeschlossen werden können. Je nach Studienumgebung kann es sinnvoll sein, Kopfhörer mit Geräuschunterdrückung zu verwenden.