---
lang: de
title: "Mögliche Alternativen für Schulen ohne ausreichende technische Ausstattung"
---

Für Schulen, die keine oder eine unzureichende technische Ausstattung haben, um die VERA-Test im regulären Onlineformat durchzuführen, bestehen folgende Alternativen:

# Nutzung alter Papiertests

Entsprechend eines Vorschlags der AG-Länderaustausch werden für einen Übergangszeitraum bzw. bis zur vollständigen digitalen Testung alte Papiertests auf Basis der alten Bildungsstandards eingesetzt. Dies hätte den Vorteil, dass bewährte Testpakete, inklusive aller Begleitmaterialien wie Auswertungsanleitungen, Durchführungserläuterungen, Itemkennwertetabellen, Didaktische Handreichungen, Dateneingabemasken etc. vorliegen. Allerdings wäre es aller Voraussicht nach nicht möglich, die erzielten Ergebnisse auf der neuen Metrik zu berichten, die auf den weiterentwickelten Bildungsstandards und digitaler Testung basiert. Diese Schulen müssten also eine auf der alten Metrik basierende Rückmeldung erhalten.

# Offlinetestung

Die Online-Testung wird lokal, d. h. ohne Internetanbindung durchgeführt. Das IQB-Testcenter ist eine Webanwendung, d. h. sie muss auf einem Server installiert werden, der über den jeweiligen Webbrowser auf den Endgeräten erreichbar sein muss. Sollte eine Schule keine oder eine zu schlechte Internet-Verbindung haben, kann als Server auch ein Laptop eingerichtet und vor Ort per Kabel an einen WLAN-Access-Point angeschlossen werden. Das Einrichten des Servers und des Access-Points ist [hier beschrieben](/setup/offline/index.qmd/).

Die Entwicklung einer Offlinevariante, bei der eine App lokal, also nicht über einen Laptop mit Serverfunktion, auf einem Tablet oder PC läuft, ist im TBA-Konzept nicht vorgesehen und wird in näherer Zukunft nicht zur Verfügung gestellt werden können. 
