---
lang: de
title: "Schulausstattung"
---

# Hardware

Es wird ein einsatzfähiges Endgerät pro Schüler\*in benötigt sowie mindestens ein vollständiger Klassensatz pro Schule. Folgende Konfigurationen sind möglich:

<table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=614
 style='width:460.45pt;margin-left:-5.3pt;border-collapse:collapse;mso-yfti-tbllook:
 160;mso-padding-alt:0cm 5.4pt 0cm 5.4pt'>
 <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
  <td width=121 valign=top style='width:90.6pt;border-top:solid windowtext 1.0pt;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:none;
  mso-border-top-alt:solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><b><span style='font-size:10.0pt;line-height:115%;
  font-family:"Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'><o:p>&nbsp;</o:p></span></b></p>
  </td>
  <td width=164 valign=top style='width:123.25pt;border-top:solid windowtext 1.0pt;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:none;
  mso-border-top-alt:solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><b><span style='font-size:10.0pt;line-height:115%;
  font-family:"Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>PC<o:p></o:p></span></b></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border-top:solid windowtext 1.0pt;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:none;
  mso-border-top-alt:solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><b><span style='font-size:10.0pt;line-height:115%;
  font-family:"Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Laptop<o:p></o:p></span></b></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border-top:solid windowtext 1.0pt;
  border-left:none;border-bottom:solid windowtext 1.0pt;border-right:none;
  mso-border-top-alt:solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><b><span style='font-size:10.0pt;line-height:115%;
  font-family:"Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Tablet<o:p></o:p></span></b></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:1'>
  <td width=121 valign=top style='width:90.6pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Eignung als
  Testgerät für SuS<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.25pt;border:none;border-bottom:
  solid windowtext 1.0pt;mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:
  solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;padding:
  0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span
  style='font-size:10.0pt;mso-bidi-font-family:"Open Sans"'>ja (empfohlen für
  Sek I)<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span
  style='font-size:10.0pt;mso-bidi-font-family:"Open Sans"'>ja (empfohlen für
  Sek I)<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span
  style='font-size:10.0pt;mso-bidi-font-family:"Open Sans"'>ja (empfohlen für
  Primarstufe)<o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:2;height:22.0pt'>
  <td width=121 rowspan=2 valign=top style='width:90.6pt;border:none;
  border-bottom:solid windowtext 1.0pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt;height:22.0pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Eignung als
  Gerät für die Teststeuerung <o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.25pt;border:none;mso-border-top-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:22.0pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span
  style='font-size:10.0pt;mso-bidi-font-family:"Open Sans"'>ja<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;mso-border-top-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:22.0pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span
  style='font-size:10.0pt;mso-bidi-font-family:"Open Sans"'>ja<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;mso-border-top-alt:
  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt;height:22.0pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span
  style='font-size:10.0pt;mso-bidi-font-family:"Open Sans"'>ja, eigeschränkt
  (häufiges Scrollen)<o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:3;height:45.25pt'>
  <td width=493 colspan=3 valign=top style='width:369.85pt;border:none;
  border-bottom:solid windowtext 1.0pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt;height:45.25pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt'><span
  style='font-size:10.0pt;mso-bidi-font-family:"Open Sans"'>Ein Gerät für die
  Teststeuerung durch Lehrkräfte/Testleitungen ist nur erforderlich, wenn die
  Gruppenmonitor für die Testdurchführung verwendet wird (optional möglich).<o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:4'>
  <td width=121 valign=top style='width:90.6pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Tastatur,
  Maus/Touchpad<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.25pt;border:none;border-bottom:
  solid windowtext 1.0pt;mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:
  solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;padding:
  0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Tastatur, Maus<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Tastatur, Maus
  (Trackpad/Trackball nur, wenn die Nutzung vertraut ist)<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>virtuelle
  Tastatur (extern optional)<o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:5'>
  <td width=121 valign=top style='width:90.6pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Empfohlene
  Bildschirmgröße und -auflösung<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.25pt;border:none;border-bottom:
  solid windowtext 1.0pt;mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:
  solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;padding:
  0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>min. 19 Zoll, HD<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>min. 13 Zoll, HD<o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.3pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>mind. 10 Zoll,
  HD<o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:6'>
  <td width=121 valign=top style='width:90.6pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Audio<sup>a</sup><o:p></o:p></span></p>
  </td>
  <td width=493 colspan=3 valign=top style='width:369.85pt;border:none;
  border-bottom:solid windowtext 1.0pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Audioausgang mit
  3,5-mm-Klinkenstecker, ggf. Adapter für USB/Lightning-Anschluss, Kopfhörer<i><o:p></o:p></i></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:7'>
  <td width=121 valign=top style='width:90.6pt;border:none;border-bottom:solid windowtext 1.0pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-bottom-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Stromversorgung <o:p></o:p></span></p>
  </td>
  <td width=164 valign=top style='width:123.25pt;border:none;border-bottom:
  solid windowtext 1.0pt;mso-border-top-alt:solid windowtext .5pt;mso-border-top-alt:
  solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;padding:
  0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>i.d.R.
  Stromanschluss<o:p></o:p></span></p>
  </td>
  <td width=329 colspan=2 valign=top style='width:246.6pt;border:none;
  border-bottom:solid windowtext 1.0pt;mso-border-top-alt:solid windowtext .5pt;
  mso-border-top-alt:solid windowtext .5pt;mso-border-bottom-alt:solid windowtext .5pt;
  padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Zugang zu
  Steckdosen/Ladestationen empfohlen<o:p></o:p></span></p>
  <p class=Absatz align=left style='margin:0cm;margin-bottom:.0001pt;
  text-align:left'><span style='font-size:10.0pt;line-height:115%;font-family:
  "Source Sans 3",sans-serif;mso-bidi-font-family:"Open Sans"'>Akkubetrieb:
  min. 120min VERA, 240min Bildungstrend <o:p></o:p></span></p>
  </td>
 </tr>
 <tr style='mso-yfti-irow:8;mso-yfti-lastrow:yes'>
  <td width=614 colspan=4 valign=top style='width:460.45pt;border:none;
  mso-border-top-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt'>
  <p class=MsoNormal style='margin-bottom:0cm;margin-bottom:.0001pt;line-height:
  normal'><i><span style='font-size:9.0pt;mso-bidi-font-family:"Open Sans"'>Anmerkungen.
  </span></i><span style='font-size:9.0pt;mso-bidi-font-family:"Open Sans"'>SuS:
  Schüler\*innen;<i> </i><sup>a </sup>nur erforderlich in den Kompetenzbereichen
  Sprachgebrauch im Fach Deutsch und Zuhören in den Fächern Deutsch,
  Englisch/Französisch.<i><o:p></o:p></i></span></p>
  </td>
 </tr>
</table>

# Software

* Betriebssystem: Windows ab Version 10; für MacOS, ChromeOS, iPadOS und Android werden jeweils die letzten zwei Hauptversionen unterstützt
* möglichst aktuelle Browserversion: 
  * Als Standard-Browsers empfiehlt das IQB nachdrücklich die Verwendung des kostenfreien Safe Exam Browsers (SEB), um die Testbearbeitung in einem abgesicherten Vollbildmodus (Kioskmodus/geführter Zugriff) sicherzustellen, den die Schüler\*innen nicht verlassen können. Der [SEB](https://safeexambrowser.org) ist als Open-Source-Software im Bildungsbereich – u. a. bei digitalen Prüfungen an Hochschulen – weit verbreitet. Der Browser sperrt nicht zulässige Funktionen wie das Wechseln zu anderen Browsertabs oder Programmen, Copy-Paste und Screenshots. Plattformabdeckung: Windows, MacOS, iPadOS. Mehr zum Thema SEB ist auch [hier](../devices/kiosk/seb.qmd) zu finden.
  * Sollte der SEB nicht verwendet werden können, empfiehlt das IQB die Verwendung (a) einer der folgenden Browser in (b) Kombination mit dem systemeigenen Kioskmodus (manuelle Einstellung):
    (a) Chrome (letzte Version), Firefox (letzte zwei Versionen und ESR-Version), Edge (letzte zwei Hauptversionen), Safari (letzte zwei Hauptversionen)
    (b) iPadOS: Geführter Zugriff <br/>
Android: über Screen Pinning / App Pinning <br/>
ChromeOS: über Admin Konsole (nur mit Google Workspace/ G Suite, Education-Domain)  
* Unterstützung für HTML5 und JavaScript
* Zugriff auf die Testumgebung: ggf. müssen Schulfilter bzw. Jugendschutzsoftware, die den Zugriff blockieren könnten, abgeschaltet werden 
* Unterbindung von automatischen Updates, geplanten Neustarts oder automatischem Standby während der Testzeit

# Netzwerkinfrastruktur

Wie bei anderen gängigen Onlineanwendungen (z. B. fachspezifische Software wie Phet und GeoGebra, Kollaborations- und Cloud-Dienste wie Nextcloud oder Lernanwendungen wie Bettermarks) hängt die Ladezeit (hier: der Testinhalte) von verschiedenen Faktoren ab. Neben dem Umfang des Tests (Testvolumen) wird die Ladezeit insbesondere durch die Leistungsfähigkeit der Endgeräte, deren Anbindung an das Netzwerk innerhalb einer Schule (einschließlich Verkabelung im Haus) sowie die Anbindung des Schulnetzwerks an das Internet bestimmt. Die Mindestvoraussetzungen für die Durchführung von Onlinetests entsprechen den Empfehlungen anderer gängiger Onlineanwendungen:

* mindestens 40 Mbit Downloadgeschwindigkeit 
* stabiles WLAN mit hoher Reichweite und genügend leistungsfähigen Access Points für die gleichzeitige Nutzung durch eine oder mehrere Klassen; LAN-Verbindungen für feststehende Computer
* Netzwerkoptimierung für den gleichzeigen Zugriff vieler Nutzer\*innen (z. B. QoS-Einstellungen für priorisierten Datenverkehr) 

Das IQB empfiehlt, die Passung der Schulausstattung zu den Anforderungen der jeweiligen Testung vor der Durchführung mit einem Systemcheck zu überprüfen. Beim Einsatz des IQB-Testcenters kann dafür z. B. der [Systemcheck](../system-check/index.qmd) der Testcenterprogrammierung verwendet werden. In den bisherigen IQB-Studien hat sich der Systemcheck im Vorfeld der Testung als hilfreich erwiesen. Dabei wird mit einem typischen Testgerät zur geplanten Testzeit (z. B. vormittags) im vorgesehenen Raum geprüft, ob die Downloadgeschwindigkeit für das Testvolumen ausreicht, die Browserversion aktuell ist und Audios sowie Videos problemlos abgespielt werden können. Zusätzlich können weitere Informationen eingeholt werden, etwa zur Häufigkeit von Netzwerkproblemen oder zu blockierten Inhalten durch Schulfilter. Diese Kriterien helfen dabei einzuschätzen, an welchen Schulen die Durchführung voraussichtlich möglich ist. Es empfiehlt sich, bei der Nutzung eines eigenen Systemchecks ähnlich vorzugehen. 
