---
lang: de
title: "Serverausstattung und -management"
---

# Lasttest

Wie bei anderen Onlineanwendungen, die in Schulen genutzt werden (z. B. Lernplattformen), ist auch für die Durchführung von Onlinetests eine geeignete Serverinfrastruktur erforderlich. Diese wird in der Regel nach landesspezifischen Kriterien konfiguriert. Um sicherzustellen, dass die vorhandene Ausstattung ausreicht und die erforderlichen technischen Parameter erfüllt, ist ein Lasttest erforderlich. Dieser simuliert eine typische Testdurchführung und liefert wichtige Informationen darüber, wie viele Testpersonen gleichzeitig den Test starten können und wie lange das Laden der Inhalte dauert. Auf Basis dieser Daten lassen sich Rückschlüsse auf die notwendige Serverkapazität ziehen.

Weitere Informationen zur Vorbereitung und Durchführung eines Lasttests für Onlinetestungen sind [hier abrufbar](/setup/availability/load-test.qmd). 

Vor dem Start eines Lasttests sollten folgende Aspekte geklärt werden:

## Wie groß ist die Datenmenge, die geladen werden soll?

Die erforderliche Datenmenge hängt vom Umfang eines typischen Tests ab. Das Testvolumen liegt in der Regel zwischen 20 und maximal 50 MB. Dabei ist zu berücksichtigen, dass ein Test bereits gestartet werden kann, sobald der erste Testabschnitt (z. B. allgemeine Hinweise) geladen ist. Im Rahmen der sogenannten Lazy-Loading-Strategie werden alle weiteren Testinhalte blockweise im Hintergrund nachgeladen. Vor dem Lasttest ist daher festzulegen, ob Lazy Loading aktiviert wird und ob sich die zu simulierende Datenmenge nur auf den Startblock beziehen soll. Eine zu kurze oder unvollständige Ladesimulation kann die Ergebnisse des Lasttests verfälschen.

Lazy Loading eignet sich insbesondere für den Einsatz in Schulen mit älteren Endgeräten (z. B. mit begrenztem RAM) und eingeschränkter Netzwerkbandbreite, da es die Systembelastung reduziert.

Beispiel: Der digitale VERA-8-Test 2025 im Fach Deutsch umfasst die Kompetenzbereiche Sprachgebrauch und Zuhören (jeweils 40 Minuten). Das gesamte Datenvolumen beträgt – je nach Modulkombination (Basismodul + leichtes oder schweres Ergänzungsmodul) – zwischen 38,0 MB und 41,8 MB. Diese Datenmenge verteilt sich auf einzelne Testabschnitte bzw. Blöcke (Instruktion: 3,5 MB; Basismodul: 0,3–13,3 MB; Ergänzungsmodul: 0,3–9,3 MB), die während der Bearbeitung schrittweise im Hintergrund geladen werden. Dadurch verkürzt sich die Startzeit, die RAM-Auslastung bleibt eher gering, die Netzwerklast wird gleichmäßiger verteilt. Dadurch sinkt das Risiko von Verbindungsabbrüchen.

## Wie viele Personen sollten sich maximal gleichzeitig anmelden können?

Hierbei ist der höchste zu erwartende Wert relevant – also die Anzahl der Personen, die sich „zur gleichen Sekunde“ einloggen. Dieser Wert kann anhand der Gesamtzahl der Testpersonen, der verfügbaren Testtage und einer angenommenen Verteilung über den Tag bestimmt werden.

## Welche Ladezeit ist noch akzeptabel?

Dies hängt unter anderem von organisatorischen Aspekten der Testdurchführung ab (z. B. kann eine Ladezeit durch allgemeine Hinweise oder Instruktionen zum Testablauf überbrückt werden). Gleichzeitig sollte die Wartezeit so kurz wie möglich gehalten werden, um die Testmotivation nicht negativ zu beeinflussen. 
Neben der Effizienz des Programmcodes der Webanwendungen, die in der Verantwortung des IQB liegt, bestimmen folgende Faktoren die erforderliche Serverkapazität:
	Anzahl der Prozessorkerne und Größe des Arbeitsspeichers (RAM)
	Leistungsfähigkeit des Datenspeichers
	Netzanbindung des Servers (Bandbreite)
	Einsatz von Lastverteilungssystemen
	Maßnahmen zur Datensicherheit (z. B. Firewalls)
Diese Übersicht verdeutlicht, dass keine allgemeingültigen Leistungsanforderungen für die Serverinfrastruktur festgelegt werden können. Vielmehr hängen die technischen Anforderungen von den spezifischen Bedingungen im jeweiligen Land ab.

# Technische Faktoren für die Serverkapazität

Neben der Effizienz des Programmcodes der Webanwendungen, die in der Verantwortung des IQB liegt, bestimmen folgende Faktoren die erforderliche Serverkapazität:

* Anzahl der Prozessorkerne und Größe des Arbeitsspeichers (RAM)
* Leistungsfähigkeit des Datenspeichers
* Netzanbindung des Servers (Bandbreite)
* Einsatz von Lastverteilungssystemen
* Maßnahmen zur Datensicherheit (z. B. Firewalls)

Diese Übersicht verdeutlicht, dass keine allgemeingültigen Leistungsanforderungen für die Serverinfrastruktur festgelegt werden können. Vielmehr hängen die technischen Anforderungen von den spezifischen Bedingungen im jeweiligen Land ab.
