---
lang: de
title: "Testorganisation"
---

Um mögliche Lücken zwischen der erforderlichen Serverkapazität und den im Lasttest ermittelten Werten zu verringern, können neben einem Ausbau der technischen Infrastruktur auch organisatorische Maßnahmen zur Optimierung der Testdurchführung beitragen:

# Streckung des Testzeitraumes

Eine Teilung der Testpopulation mit versetztem Testbeginn um eine (Unterrichts-) Stunde würde die tägliche Kapazität zum Beispiel verdoppeln. Eine weitere Ausdehnung der Testphase auf eine Woche könnte die Last zusätzlich reduzieren.

# Paralleler Einsatz mehrerer getrennter Server

Durch das Aufsetzen separater Server mit jeweils eigener Testcenter-Installation kann die Testpopulation gezielt auf einzelne Server verteilt werden. Die Antwortdaten müssten anschließend zusammengeführt werden.

Einzelne Länder haben durch eigene Lasttests bereits umfangreiche Erkenntnisse zur Konfiguration der benötigten Serverinfrastruktur und die Planung der Testorganisation gesammelt. Diese Länder könnten gebeten werden, ihre Erkenntnisse und Erfahrungen zur Verfügung zu stellen bzw. in bestehende Austauschgremien (z. B. AG-Länderaustausch, VERONA-Forum) einzubringen.
