---
lang: de
title: Zahlenstrahl
---

## Zahlenstrahl

1. Gewünschte Datei in GeoGebra öffnen: 

   a. Vollständige Vorlage Zahlenstrahl: schon mit bearbeitbaren Punkten zum Platzieren 
   b. Vorlage Zahlenstrahl: nur der Zahlenstrahl (KEINE Punkte zum Platzieren) 
   c. Hierbei sind die Versionen „ohne Zahlen“ unbeschriftete Zahlenstrahle 

2. Zum Bearbeiten des Zahlenstrahls 4 Parameter anpassen: 

   a. Startwert: Startwert des Zahlenstrahls 
   b. Endwert: Endwert des Zahlenstrahls 
   c. Abschnitte: Anzahl der (beschrifteten) Abschnitte 
   i. Hinweis: Wenn sehr präzise platziert werden soll, dürfen nicht zu viele Abschnitte eingestellt werden 
   d. Teile pro Abschnitt: Unterabschnitte pro Abschnitt (nur bei Vorlage „+große_Striche“) 

3. Wenn vollständige Vorlage gewählt: 

   a. Gewünschte Anzahl an blauen Punkten beibehalten, überzählige Punkte + Beschriftungen löschen 
      i. Hinweis: Die blauen Punkte „springen“ absichtlich in der Senkrechten auf den Zahlenstrahl, um die Bearbeitbarkeit zu vereinfachen. Genauso absichtlich springen sie in der Waagerechten nicht von Strich zu Strich, um auch Platzierungen dazwischen zu ermöglichen. 
   b. rechts oben auf die 3 Striche mit den Formen und dann auf das Zahnrad klicken, um die Einstellungen zu öffnen 
   c. Auf zu ändernde Beschriftung eines Punkts klicken und rechts in den Einstellungen die Beschriftung anpassen 
   d. Danach unter „Erweitert“ den Haken bei „Auswahl erlaubt“ entfernen 

4. Die 4 Eingabefelder (Startwert etc.) löschen (mit Rechtsklick + löschen klicken) oder unsichtbar machen, falls Sie diese später noch einmal bearbeiten möchten.
