---
lang: de
title: "Studie durchführen mit dem Testcenter"
---

::: {.callout-note}
Vor der Durchführung dieser Schritt für Schritt Anleitung, wird empfohlen alle Texte im Kapitel: **Testcenter** zu lesen. An dieser Stelle finden keine Erklärungen zu Themen statt, die bereits an anderer Stelle erfolgt sind. 
:::

An dieser Stelle soll eine kleine exemplarische Studien durchgeführt werden. Anwender\*innen sollen so ein besseres Gefühl für das Testcenter bekommen.

## Anforderungen an die Beispielstudie

* Die Studie soll aus insgesamt 2 Aufgaben bestehen. 
* Es soll eine Seite zur Begrüßung und eine weitere zur Verabschiedung geben. Aufgabe 1 enthält ein Audio. Dieses muss abgespielt werden damit ein weiterer Abschnitt erscheint mit Pflichtfragen zu diesem Audio. In Aufgabe 2 wird ein Video angezeigt und es werden Fragen dazu gestellt.
* Solange das Pflichtelement in Aufgabe 1 nicht bedient wurde und nicht alles gesehen oder angehört wurde, ist ein Weiterblättern zur Aufgabe 2 nicht möglich. Rückwärts kann Aufgabe 1 jederzeit, auch ohne Beantwortung und ohne alles betrachtet oder angehört zu haben, verlassen werden. Aufgabe 2 enthält keine Pflichtelemente und kann daher ohne Beantwortung in beiden Richtungen verlassen werden. Es muss aber alles betrachtet werden, um vorwärts blättern zu dürfen. Auf der Begrüßungs- und Verabschiedungsseite befinden sich keine Elemente zur Beantwortung, daher können diese Seiten jederzeit in beiden Richtung verlassen werden. Um die Seite vorwärts zu verlassen zu können, müssen zuvor alle Inhalte betrachtet werden.
* Zur Navigation soll eine entsprechende Navigationsleiste mit den Nummern der Aufgaben angezeigt werden. Außerdem soll ein Navigationsmenu zu sehen sein, mit welchem der Test auch beendet werden kann. 
* Die Aufgabe 1 und 2 sollen sich in einem Block befinden. Der Block kann erst betreten werden, wenn das richtige Freigabewort eingegeben wurde. Außerdem soll der Block über eine Zeitbeschränkung von 3 Minuten verfügen. Die verbleibende Zeit soll angezeigt werden.
* Im Kopf soll der Aufgabenname **nicht** angezeigt werden. 
* Der Test soll im Modus: **run-hot-return** durchgeführt werden. 
* Der Test kann nach Beendigung jederzeit weiterbearbeitet werden. Natürlich nur solange die Blockzeit noch nicht abgelaufen ist. 
* Es sollen 3 Testpersonen Zugriff auf die Studie haben. Diese müssen sich mit Namen und Passwort am Testcenter anmelden. 
* Es ist ein Gruppenmonitor vorzusehen mit dem der Bearbeitungsstand der 3 Testpersonen verfolgt werden kann.