---
lang: de
title: "Markieren-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

# Assistent-Markieren

Der Assistent „Markieren“ ermöglicht das Erstellen von Aufgaben, bei denen Textabschnitte markiert werden können.

## Beispiel
 
Im Assistenten fügen Sie die gewünschte Fragestellung ein und wählen den Stimulustext aus, in dem markiert werden soll. Anschließend bestimmen Sie den Markiermodus. Außerdem können Sie ein Bild mit Hilfstext einfügen, das den Testteilnehmenden das Markiertool erklärt.
Unter der Aufgabe erscheinen ein Stift- und ein Radiergummi-Symbol.
Mit Hilfe des Stifts können Testteilnehmende das gewünschte Wort oder den gewünschten Bereich markieren und mit dem Radierer können sie eine bestehende Markierung wieder entfernen.

## Text
 
Die Fragestellung wird im Texteditor des Studios verfasst. Weitere Details dazu finden Sie hier: [Editor](../Medienelemente/Text/index.qmd)

## Verbundener Stimulustext
 
Wählen Sie außerdem den Stimulustext, in dem etwas markiert werden soll, aus.
 
Die ID des gewünschten Textelementes sehen Sie, wenn Sie im Editor auf das jeweilige Textelement klicken.

## Markiermodus
 
Unter Markiermodus können Sie auswählen, ob Sie einzelne Worte oder Sätze bzw. Bereiche markieren wollen. 

## Hilfe
 
Durch das Setzen des Hakens bei „Bild mit Hilfstext anfügen“ erscheint die Glühbirne neben der Aufgabenstellung.
 
In der Aufgabe erscheint eine Informations-Glühbirne, je nachdem ob ein Bereich oder ein Wort markiert werden soll. Wenn Sie den Mauszeiger darüber bewegen, wird ein Informationstext eingeblendet.

## Bestätigen/Abbrechen

Wenn Sie mit allen Eingaben zufrieden sind, klicken Sie auf „Bestätigen“ und der Assistent erstellt die Markieraufgabe im Studio für Sie. Um Ihre Eingaben zu verwerfen klicken Sie auf Abbrechen. Achtung: In diesem Fall gehen sämtliche Angaben verloren und Sie müssten erneut von vorne beginnen.
