---
lang: de
title: "Drag & Drop-Zuordnen-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

# Drag & Drop-Zuordnen

Der Assistent „Drag & Drop – Zuordnung“ hilft Ihnen beim Erstellen von Drag and Drop Aufgaben mit textbasierten und/oder bildbasierten Antwortoptionen. 

Im Assistenten geben Sie die Fragestellung bzw. Instruktion und optional eine Überschrift für die Elementliste der Antwortoptionen ein. Anschließend fügen Sie die Antwortoptionen ein und können optional eine Überschrift und Beschriftungen für die Zielablageliste eingeben.

## Frage/Instruktion
 
Die Frage/Instruktion wird im Texteditor des Studios verfasst. Weitere Details dazu finden Sie hier: [Editor](../../Medienelemente/Text/index.qmd)

## Elementliste
 
Die Überschrift der Elementliste kann optional im Texteditor des Studios eingegeben werden. Weiteres zum Texteditor finden Sie hier: [Editor](../../Medienelemente/Text/index.qmd).

Bevor Sie Elemente im Eingabefeld einfügen, wählen Sie deren ungefähre Länge aus.

Fügen Sie nun die Elemente im entsprechenden Feld ein und bestätigen Sie mit Enter oder mit Klick auf das Plus rechts.  

 
Bei Bedarf kann jede Zeile gelöscht werden oder das Wort angepasst werden. Klicken Sie hierfür auf den blauen Schraubenschlüssel. Dadurch öffnet sich ein Menü und Sie können die Änderungen in einem auftauchenden Fenster vornehmen.

## Ziel-Ablagen
 
Bei den Zielablagen benennen Sie die Ablagen, in die die Elemente verschoben werden sollen. Die einzelnen Bestandteile (Überschrift, Zielbeschriftung und Länge der Zielbeschriftungen) verhalten sich identisch mit denen der Elementliste.

Wie zuvor bei den Elementen bestimmen Sie zunächst die ungefähre Länge für die Zielbeschriftungen und können dann die Zielbeschriftungen in das Eingabefeld eingeben. 
Zum Ändern der Wörter können Sie auf den Schraubenschlüssel klicken. Zum Löschen eines Wortes klicken Sie auf das Plus.

::: {.callout-note}
Über das   Symbol bearbeiten Sie die jeweiligen Elemente und mit dem  löschen Sie diese. So können Sie nachträglich die Texte, Bilder oder Audios noch austauschen.
:::

## Ausrichtung
 
Wenn Sie die Elementliste über der Zielliste haben möchten, wählen Sie dies bei Ausrichtung aus. Mit der Einstellung „Elementliste über Ziellisten“ befinden sich diese jeweils übereinander. Diese Einstellung eignet sich besonders bei vielen Elementen.

Wenn die Elementliste seitlich angeordnet sein soll, wählen Sie diese Variante bei der Ausrichtung aus. Mit der Einstellung „Elementliste neben Ziellisten“ ordnen sich diese kompakter nebeneinander an. Diese Einstellung ist besonders für kurze Elemente und einseitige Aufgaben geeignet. 
 
## Bestätigen/Abbrechen
Wenn Sie mit allen Eingaben zufrieden sind, klicken Sie auf Bestätigen und der Assistent erstellt die Aufgabe im Studio für Sie. Um Ihre Eingaben zu verwerfen, klicken Sie auf Abbrechen. Achtung: In diesem Fall gehen sämtliche Angaben verloren und Sie müssten erneut von vorne beginnen.

## Nachträgliches bearbeiten

Sie können im Nachhinein noch einstellen, welche Ablegelisten miteinander verbunden sind. Wählen Sie dazu unter „Verbundene Ablegelisten“ die ID der gewünschten Liste. Beachten Sie, dass sich damit Elemente von der aktuellen in die verbundene Liste verschieben lassen. Umgekehrt ist dies aber nur möglich, wenn auch bei der anderen Liste die Verbindung eingestellt ist. 

::: {.callout-note}
Bei manueller Veränderung, welche Ablegelisten miteinander verbunden sind, können schnell Fehler unterlaufen. Sollten Sie sich dafür entscheiden, die Verbindungen nachträglich zu bearbeiten, dann wird empfohlen, ausführlich zu testen, ob die Funktionalität der Aufgabe erhalten bleibt. 
:::

Um die Breite der Ablegelisten zu verändern, setzen Sie eine neue Maximalbreite. Bitte beachten Sie, dass aus optischen Gründen meist eine einheitliche Maximalbreite ideal ist.

Sie können die Elemente in der Ablegeliste auch nachträglich noch bearbeiten. Klicken Sie dafür auf die Ablegeliste. Mit dem Plus können Sie neue Elemente hinzufügen, mit dem Schraubenschlüssel neben einem Element können Sie dieses bearbeiten und mit dem Kreuz können Sie es löschen. Sie können auch die Reihenfolge der Elemente durch Verschieben ändern.