---
lang: de
title: "Drag & Drop - Weiterleitung"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

# Assistent: Drag and Drop 
Sie können aus verschiedenen Drag & Drop Formaten wählen. „Drag & Drop: Zuordnung“ hilft beim Erstellen von Drag and Drop Aufgaben mit textbasierten und/oder bildbasierten Antwortoptionen. „Drag & Drop – Sortieren“ ermöglicht das Erstellen einer Aufgabe, bei der Elemente in ihrer Reihenfolge verändert werden sollen.
 
## Zuordnung
Mit diesem Assistenten legen Sie eine einseitige Drag & Drop Aufgabe mit textbasierten und/oder bildbasierten Antwortoptionen an. Weitere Details dazu finden Sie hier: [Drag&Drop Zuordnen](DaD_Assistent_Zuordnung/index.qmd)

## Zuordnung (2-seitig)
Mit diesem Assistenten legen Sie eine zweiseitige Drag & Drop Aufgabe mit textbasierten und/oder bildbasierten Antwortoptionen an. Weitere Details dazu finden Sie hier: [Drag&Drop Zuordnen:2-seitig](DaD_Assistent_Zuordnung_zweiseitig/index.qmd)

## Sortieren
Mit diesem Assistenten legen Sie eine einseitige Drag & Drop Aufgabe mit textbasierten und/oder bildbasierten Antwortoptionen, die sich fest in einer einzelnen Liste befinden und in ihrer Reihenfolge verändert werden sollen, an. Weitere Details dazu finden Sie hier: [Drag&Drop Sortieren](DaD_Assistent_Sortieren/index.qmd)