---
lang: de
title: Zugriffsrechte
---

Die Startseite des Testcenters bietet ein Eingabeformular zum Login. Für alle Zugriffsrechte im System muss nach der Eingabe von Benutzername und Kennwort der Button **Weiter als Admin** geklickt werden.

# Super-Admin

Nach der Eingabe der Zugangsdaten als Super-Admin werden ggf. Arbeitsbereiche aufgelistet und es ist außerdem ein Schalter für die **Systemeinstellungen** zu sehen. Wird dieser Schalter betätigt, wird eine weitere Seite geladen, die die folgenden 3 Reiter anzeigt:

* **Users:**<br>
Hier können bestehende Nutzer\*innen (Workspace-Admins) verwaltet werden. Es können mittels Plus-Schaltfläche neue Nutzer\*innen hinzugefügt werden oder mit der Löschen-Schaltfläche gelöscht werden. Weiterhin stehen zwei Schaltflächen zur Änderung von Kennwort und Zugriffsebene bereit. Diese beide Schaltflächen sind mit einem Stift-Symbol gekennzeichnet. Ist eine Person als Super-Admin angelegt, wird diese mit einem Stern in der Liste der Nutzer\*innen geführt. Wird in der Liste eine Person markiert, werden auf der rechten Seite alle Arbeitsbereiche angezeigt auf die diese Person Zugriff hat. Die Berechtigung für einen Arbeitsbereich sind noch einmal unterteilt in "read only" (RO) und "read and write" (RW).

* **Arbeitsbereiche:**<br>
Hier werden alle angelegten Bereiche aufgelistet. Es können neue Bereiche angelegt, gelöscht oder nachträglich bearbeitet werden. Durch Markierung eines Bereichs werden rechts alle Personen aufgelistet, die auf diesen Bereich Zugriff haben. Dabei wird noch einmal unterschieden, ob die Personen nur lesend (RO) oder lesend und schreibend (RW) auf den Bereich zugreifen darf. Sollen Personen einen Zugriff auf einen Bereich erhalten, ist der jeweilige Bereich zu markieren und die Person mit RO- oder RW-Zugriff auszuwählen. Anschließend muss zwingend das Speicher-Symbol oben rechts aktiviert werden, ansonsten werden die Änderungen nicht gespeichert.

* **Einstellungen:**<br>
Hier können einige Bereiche des Testcenters an individuelle Bedürfnisse angepasst werden. Es ist bspw. möglich das Logo auszutauschen, die Hintergrundfarbe und Texte der Anwendung zu verändern. Es können auch Textersetzungen für die Bereiche: Testheft, Gruppenmonitor, Login und System-Check erfolgen. Sollen Texte ersetzt werden, ist nach Änderungen zwingend die Speichern-Schaltfläche zu betätigen, um die Änderungen zu übernehmen.

# Arbeitsbereich

Zur Organisation von Studien stehen Arbeitsbereiche zur Verfügung. Diese legen die Super-Admins an und vergeben die entsprechenden Berechtigungen. Die Benennung dieser Bereiche richtet sich günstigerweise nach dem Zweck der Studie.

Nach der Anmeldung präsentiert das System eine Liste aller Arbeitsbereiche, die für eine Person freigegeben sind. Mit einem Klick auf den jeweiligen Arbeitsbereich wird dieser geöffnet. Zur Liste der Arbeitsbereiche kehrt man zurück, indem man auf das IQB-Logo links oben in der Ecke klickt.

Nutzer\*innen, die mit einem solchen Zugang arbeiten, können Daten in Arbeitsbereiche laden und Daten aus einem Bereich herunterladen. Sie haben keinen Zugriff auf andere Stelle des Testcenters. 

::: {.callout-note}
Als Arbeitsbereichs-Admin werden alle eingerichteten Zugänge zum Testcenter bezeichnet, die nicht mit Super-Admin-Rechten ausgestattet sind.
:::

Anschließend sehen Workspace-Admins alle für sie freigegebenen Arbeitsbereiche. Durch ein Klick auf einen Arbeitsbereich, können Daten in den Arbeitsbereich geladen werden. Falls Antwortdaten vorhanden sind, können diese heruntergeladen werden.


Der Arbeitsbereich hat drei Grundfunktionen. Diese können mit einem Klick auf den entsprechenden Reiter ausgewählt werden:

* Dateien: Testinhalte hochladen, austauschen, löschen
* System-Check Berichte: Herunterladen der Berichte aus den System-Checks
* Ergebnisse/Antworten: Herunterladen der Antworten, Logs und der Kommentare aus Reviews
