---
lang: de
title: "Testcenter Überblick"
---

::: {.callout-tip appearance="minimal"}
## Codeverwaltung Testcenter

[Testcenter GitHub Repository](https://github.com/iqb-berlin/testcenter)<br>
[Testcenter Veröffentlichungen](https://github.com/iqb-berlin/testcenter/releases)
:::

Das IQB-Testcenter ist eine Webanwendung für die Durchführung von Kompetenztests oder Befragungen. 
Nach der Installation auf einem Webserver wählt man diesen Server über seine Adresse an, d. h. man schreibt 
dessen Internet-Adresse in die Adresszeile eines Internet-Browsers. Dadurch werden die Programmierungen geladen 
und man sieht ein Formular zur Anmeldung. Alle Daten (Testdateien) für einen Test sind vorher auf dem Server zu speichern. 
Das kann über ein integriertes Verwaltungsportal des Testcenters erfolgen oder über andere Webanwendungen, die auf den Server mit einer definierten Schnittstelle zugreifen.

::: {.callout-note}
Verfügbare Video-Anleitung zum Testcenter sind der Videothek zu finden.
:::

# Installation

Das IQB hat alle Programmierungen unter der Open Source-Lizenz [MIT](https://opensource.org/licenses/MIT) veröffentlicht und erleichtert die Installation durch Containervirtualisierung (Docker). Für die Installation muss man einen Linux-Server bereitstellen und dieser Server muss dann über eine Internet-Adresse erreichbar sein. Die Installation sollte erfahrenes IT-Fachpersonal durchführen. Die Dokumentation hierzu setzt Wissen vor allem zur Virtualisierungssoftware Docker voraus. Es ist weiterhin Wissen zur Datensicherheit nötig, denn sobald ein Server öffentlich verfügbar ist, müssen Maßnahmen gegen Angriffe durch Schadsoftware ergriffen werden. Das IQB ist bemüht, die Installationspakete und die eigentlichen Anwendungen gut abzusichern,übernimmt aber im Schadensfall keine Verantwortung.

# Verwaltung der Tests

Nach der Installation ist zunächst ein administratives Konto für die Verwaltung von Arbeitsbereichen und Zugangsberechtigungen angelegt, der sogenannte **Super-Admin**. Außerdem ist ein Arbeitsbereich mit Dateien für einen Beispieltest eingerichtet. Im ersten Schritt legt der Super-Admin Zugänge für einzelne Personen an und weist diesen Arbeitsbereiche zu. Die für eine Studie benötigten Testdateien werden dann in diesen Bereich geladen. Hierfür steht eine entsprechende Verwaltungsoberfläche zur Verfügung, die Bedienelemente zum laden, löschen usw. bereitstellt. Nach Abschluss einer Studie können über diese Verwaltungsoberfläche die Antworten heruntergeladen werden.

# Durchführung von Tests oder Befragungen

Durch Eingabe der Adresse des installierten Testcenters, erhält man ein Anmeldeformular. Zur Testdurchführung müssen sich hier die Testpersonen mit entsprechenden Zugangsdaten anmelden, um eine für sie eingerichtete Testung zu starten. Die gültigen Anmeldedaten werden in einer der Testdateien hinterlegt. Nach erfolgreicher Anmeldung startet dann das für diese Person vorbereitete Testheft mit einer Abfolge von Aufgaben. Folgende besonderen Funktionen sind im IQB-Testcenter derzeit umgesetzt:

* Verschiedene Varianten der Anmeldung: Anmeldung über einen Link, zweistufige Anmeldung zur Vereinfachung der Durchführung, 
spezieller Modus für das Ausprobieren eines Tests (Review) usw.
* Mehrere Testhefte: Eine Testperson kann auch mehrere Testhefte nacheinander bearbeiten mit denselben Anmeldedaten
* zeitliche Beschränkung von Testteilen: Für eine bestimmte Anzahl Aufgaben steht der Testperson eine begrenzte Zeit zur Verfügung
* Fortsetzung erst mit Freigabewort: Die Testdurchführung z. B. in einer Klasse kann synchronisiert werden, indem die Testleitung 
ein Wort ansagt, mit dem dann der Test fortgesetzt werden kann
* Fortsetzung erst nach vollständiger Präsentation: Um zu vermeiden, dass Teile einer Aufgabe übersehen werden, 
kann das Weiterblättern solange unterbunden werden, bis alle Audio-Sequenzen abgespielt wurden und alle Seiten vollständig angezeigt wurden
* Fortsetzung erst nach vollständiger Beantwortung
* sofortige Speicherung: Alle Antworten werden sofort zum Testcenter-Server gesendet; 
nach Abbruch der Testung oder Absturz eines Computers bzw. Browsers kann daher der vorherige Stand wiederhergestellt werden
* In Abhängigkeit gegebener Antworten und einer zuvor festgelegten Wichtung, kann zu bestimmten Aufgaben verzweigt werden (adaptives Testen)

Es können mehrere Tests oder Befragungen gleichzeitig laufen.

# System-Check

Man kann bei der enormen Vielfalt der Hardware (Tablet, Smartphone usw.) und Software (Apple, Linux, Android usw.) nicht garantieren, dass ein Test oder eine Befragung so wie beabsichtigt funktioniert. Je nach Anforderung an den Test wird das auch nicht sinnvoll sein, z. B. wenn eine Mindestbreite für den Bildschirm erforderlich ist.

Wenn man erfahren möchte, ob die Zielsysteme geeignet sind, kann man im IQB-Testcenter einen System-Check konfigurieren. 
Dann können z. B. die verantwortlichen Lehrkräfte in der Vorbereitungsphase im Testcenter einen auf die speziellen Anforderungen des 
Tests abgestimmten Check durchführen. Auch die Internetverbindung kann hierüber bewertet werden.

Ein System-Check sollte aber auch nicht überbewertet werden. Ein positiver Befund ist keine Garantie dafür, dass am Tag der Durchführung alles glatt läuft. Die Leistungsfähigkeit der Internetverbindung beispielsweise hängt davon ab, was parallel in der Schule gerade an Bandbreite für andere Zwecke (z. B. automatische System-Aktualisierungen) belegt ist. Außerdem erhöht ein System-Check den ohnehin hohen Aufwand einer Testung und könnte die Motivation zur Teilnahme weiter senken.

# Gruppenmonitor

Die Testleitung kann einen Gruppenmonitor einsetzen, um den Verlauf einer Studie zu beobachten oder um Teilnehmer\*innen gezielt im Testheft zu navigieren. So kann dann bspw. das Weiterleiten in andere Blöcke erzwungen, der Test pausiert, beendet oder gesperrt werden.

# Systemanforderungen Studiendurchführung

Da die Programmierungen des Testcenters online in einem Browser ablaufen, ist keine vorherige Installation von Software auf einem Computer nötig, mit dem der Test oder die Befragung durchgeführt werden soll. Es ist nur ein Internet-Zugriff und ein Browser nötig.

Es gibt immer wieder die Diskussion darüber, ob bzw. in welchem Maße ältere Browser bzw. Browserversionen unterstützt werden sollen. Hier wird argumentiert, dass Schulen bzw. deren Träger oft nicht in der Lage seien, die Verwendung aktueller Browser sicherzustellen. Aus dieser Realität ergebe sich, dass die Programmierungen für TBA stets ein Maximum an Abdeckung auch für alte Browser leisten müssten.

Das IQB folgt hier jedoch den Anforderungen an die Datensicherheit, so wie es z. B. das [Bundesamt für Sicherheit in der Informationstechnik](https://www.bsi.bund.de/) formuliert:

> "Der Internet-Browser ist die zentrale Komponente für die Nutzung von Online-Angeboten und stellt somit eins der beliebtesten Ziele für Cyber-Angriffe dar. Hieraus ergibt sich ein besonders hohes Gefahrenpotenzial." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/Der-Browser/der-browser_node.html)

> "Installieren Sie alle Aktualisierungen sofort oder zeitnah nach ihrer Veröffentlichung, sowohl die für Ihren Browser, als auch für alle Erweiterungen und natürlich Ihr Betriebssystem. Verwenden Sie stets die neuste Version Ihres Browsers." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/updates-browser-open-source-software_node.html)

Das IQB unterstützt daher nur die jeweils letzten beiden Hauptversionen eines Browsers bzw. die Versionen der letzten 12 Monate. 

**Stand April 2024:**

* Firefox: 125 und 124
* Chrome: 123 und 122
* Edge: 124 und 123
* Safari: 17 und 16

Neu veröffentliche Browserversionen können unter Umständen Änderungen enthalten, die zu einem anderen Verhalten der Anwendung führen. Das IQB ist daher bemüht die Anwendung zeitnah in Verbindung mit Neuerscheinungen zu testen, kann dies aber nicht in jedem Fall gewährleisten, da die Vielzahl an möglichen neuen Browserversionen (Safari, Edge, Chrome, Firefox) recht herausfordernd ist. Sollten bereits neuere Versionen, als die hier genannten Versionen zum Einsatz kommen, empfiehlt sich eine Voransicht vor finalem Studienlauf. Hierfür bietet das Testcenter spezielle Modi der Studiendurchführung an, wie bspw. einen Review-Mode. Für einzelne Aufgaben zur Ansicht kann auch der **System-Check** verwendet werden. 

Ist von einem fehlerhaften Verhalten der Anwendung in Verbindung mit neueren Browserversionen auszugehen, kann eine Meldung an das Entwicklerteam erfolgen.
