---
lang: de
title: "Konfiguration"
---

::: {.callout-tip}
Die Konfiguration des Studienverhaltens kann mittels der beiden XML's: XML zur Studien-Definition und XML zur Testheft-Definition vorgenommen werden. Mehr Informationen zu den beiden XML's und zu entsprechenden Listen möglicher Konfigurationswerte sind den Referenzen zu entnehmen.
:::

Es gibt eine Vielzahl von Möglichkeiten zur Konfiguration des Studienverhaltens. Es kann an dieser Stelle nicht auf alle Möglichkeiten eingegangen werden. Hier aufgezeigt werden die wichtigsten Fragen zur Konfiguration der Studie, die vor jedem Studienstart gestellt werden sollten.

## Sollen Aufgaben- und Testheftbezeichner angezeigt werden?

Das in der XML zur Aufgaben-Definition festgelegte Label einer Aufgabe und das in XML zur Testheft-Definition festgelegte Label des Testheftes, können während der Testung angezeigt werden. Dies wird in der XML zur Testheft-Definition in der Testheft-Konfiguration mit dem Wert: `unit_screenheader`und einem entsprechenden Datum aus der zugehörigen Liste festgelegt werden.

## Sollen Standardtexte der Anwendung durch eigene ersetzt werden?

Textersetzungen werden in der XML zur Studien-Definition festgelegt. Dazu müssen entsprechende Werte im XML Element `<Custom-Text>` aus einer Liste hinzugefügt werden.

## Wie sollen die Navigationsschaltflächen aussehen? Soll es überhaupt welche geben?

#### Layout

Labelshort
Aussehen

## Sollen Beschränkungen für die Navigation erfolgen (Weiterblättern erst nach Beantwortung etc.)?

responses und presentation complete

## Soll es ein zusätzliches Menu zur Navigation geben?

Unit menu

## Wie wird das Testheft aufgeteilt? Gibt es beschränkte Blöcke?

## Was soll beim verlassen eines Block geschehen? Soll der Block gesperrt werden oder darf weiter gearbeitet werden?

## Was soll geschehen, wenn der Test beendet wird? 

Test sperren oder nicht