---
lang: de
title: "Modi der Testdurchführung"
---

Jeder angelegten Testperson wird ein Modus zugewiesen. Der gewählte Modus bestimmt das Testverhalten und weist spezifische Eigenschaften und Funktionen auf. Bspw. werden in manchen Modi die gegebenen Antworten gespeichert, in anderen Modi nicht. Da jeder hinterlegten Testperson auch ein Testheft zugewiesen wird, können verschiedene Anmeldungen mit denselben Testheften zu unterschiedlichem Verhalten führen. Mit Hilfe des Modus kann aber nicht nur das Testverhalten festgelegt werden, es stehen auch spezielle Modi für die Testleitung zur Verfügung, die zur Teststeuerung und Überwachung (Gruppenmonitor) verwendet werden können.

# Wo wird das festgelegt?

Die Festlegung erfolgt in der XML zur Studien-Definition im Element `Login` mit Hilfe des Attributs `mode` und eines zugehörigen Wertes. Nachfolgend ist ein einfaches Beispiel zu sehen:

::: {.callout-important}
Die Werte des Attributs: `mode` sind nicht frei wählbar und sind einer entsprechenden Liste zu entnehmen. Hierbei ist die Groß-/Kleinschreibung zu beachten.
:::

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
  <Testtakers>
     <Metadata>
       <Description>Testbeispiel</Description>
     </Metadata>

     <Group id="tsgr1" label="Testgruppe 1">
       <Login mode="run-review" name="me4r5t6" pw="d7u9">
         <Booklet>Booklet_Version1</Booklet>
       </Login>
       <Login mode="run-hot-return" name="susz67j" pw="r4u2">
         <Booklet>Booklet_Version1</Booklet>
       </Login>
     </Group>
   </Testtakers>
```
---

In diesem Beispiel wird dem ersten Login: **me4r5t6** der Modus: `run-review` zugewiesen. Nach Anmeldung wird dieser Testperson das Booklet: **Booklet_Version1** in diesem Modus präsentiert. Wie dem Namen schon zu entnehmen ist, werden bei diesem Modus spezielle Funktionen der Vorbetrachtung bereitgestellt. Die angemeldete Person kann bspw. über eine Kommentarfunktion entsprechende Kommentare zu den Aufgaben hinterlegen. Diese Kommentare können anschließend heruntergeladen werden. Aufgabenentwickler\*innen können diese dann für eine Korrektur der Aufgaben vor finaler Testdurchführung verwenden.

Dem zweiten Login: **susz67j** wird das Testheft: **Booklet_Version1** im Modus: `run-hot-return` präsentiert. Wie der Name des Modus vielleicht schon erahnen lässt, wird die Testung "heiß" durchgeführt. Hier werden bspw. zum Zwecke der Auswertung alle Antworten gespeichert.

An dieser Stelle kann nicht auf alle Funktionen der Modis eingegangen werden. Eine nähere Beschreibung ist der Liste zu entnehmen.

::: {.callout-note icon=false}
# [Link zur Liste möglicher Modi](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/test-mode.html)

Eine Liste aller Testmodi, deren Funktionen und Beschreibungen dazu.
:::
