---
lang: de
title: "Testtaker-XML"
---

::: {.callout-note}
In Bearbeitung THuste: to do

* Überarbeiten Layout und Text

:::

# Attribute und Daten

Folgende Funktionen erfüllt die Testtaker-XML:

* Anlegen der Zugriffsdaten (Logins)
* Gruppenzuweisungen
* Gruppenbeschränkungen
* Modi der Testdurchführung
* Testheftzuweisungen
* Gruppenmonitoring
* Textersetzungen

::: {.callout-important}
Die in der XML-Datei angelegten Attribute und Elemente sind nicht frei wählbar, sondern orientieren sich an einer Schema-Definition. Diese gibt vor, welche Elemente und Attribute verwendet werden dürfen. Die Schema Definition für die Testtaker-XML ist [hier](https://github.com/iqb-berlin/testcenter/blob/master/definitions/vo_Testtakers.xsd) ersichtlich.
:::

Die Schema-Definition wird im Kopf der XML eingebunden:

```{.xml .code-overflow-wrap}
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.0.1/definitions/vo_Testtakers.xsd">

</Testtakers>
```
::: {.callout-note collapse="true"}

## Beispiel XML

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.0.1/definitions/vo_Testtakers.xsd">

<Metadata>
    <Description>
    This file contains some logins for testing and works a a sample for developers.
    </Description>
</Metadata>

<CustomTexts>
    <CustomText key="app_title">Hier steht ein Custom Text</CustomText>
</CustomTexts>

<Group id="sample_group" validFrom="1/3/2024 10:00" label="Primary Sample Group">
    <Login mode="run-hot-return" name="test" pw="user123">
        <Booklet codes="xxx">BOOKLET.SAMPLE-1</Booklet>
        <Booklet codes="yyy">BOOKLET.SAMPLE-3</Booklet>
    </Login>
    <Login mode="monitor-group" name="test-group-monitor" pw="user123"/>
</Group>

<Group id="study_group" label="A group for the study monitor">
    <!-- the study monitor has access to all other groups on the workspace -->
    <Login mode="monitor-study" name="test-study-monitor" pw="user123"/>
</Group>

<Group id="trial_group" label="A Group for Trials and Demos" validFor="45">
    <Login mode="run-trial" name="test-trial" pw="user123">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-demo" name="test-demo" pw="user123">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-simulation" name="test-simulation" pw="user123">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
</Group>

<Group id="passwordless_group" label="A group of persons without password">
    <Login mode="run-hot-restart" name="test-no-pw">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-trial" name="test-no-pw-trial">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
</Group>

<Group id="expired_group" validTo="1/3/2020 19:30" label="An already expired group">
    <Login mode="run-hot-restart" name="test-expired">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="monitor-group" name="expired-group-monitor" pw="user123"/>
    <Login mode="monitor-study" name="expired-study-monitor" pw="user123"/>
</Group>

<Group id="future_group" validFrom="26/3/2030 9:00" label="An not yet active group">
    <Login mode="run-hot-restart" name="test-future">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
</Group>

</Testtakers>
```

In diesem Beispiel sind 6 Gruppen zu finden. Diese Gruppen enthalten eine unterschiedliche Zahl von Logins, Anmeldeverfahren (mit Passwort, ohne Passwort etc.), Modi und zeitlichen Beschränkungen. 

In der ersten Gruppe: sample_group befinden sich 2 Logins. Die Gruppe verfügt über eine Zeitbeschränkung (`validFrom`). Alle dieser Gruppe zugehörigen Logins können sich erst am 01.03.2024 um 10:00 Uhr anmelden. Nach Anmeldung des ersten Logins am Testcenter, stehen je nach erfolgter Code-Eingabe 2 Testhefte zur Auswahl (BOOKLET.SAMPLE-1, BOOKLET.SAMPLE-3). Die Studie soll im Modus: run-hot-return durchgeführt werden, es werden also alle Antworten unter dem Gruppennamen: sample_group, dem Login: Test und dem entsprechenden Code gespeichert. Nach Anmeldung des zweiten Logins wird ein Gruppenmonitor präsentiert. Mit Hilfe dieses Monitor können die Aktivitäten innerhalb der Gruppe überwacht und gesteuert werden. Ist bspw. der erste Login aktiv, ist dies im Gruppenmonitor ersichtlich und die Testleitung kann die angemeldete Personen nun im Testheft zu einer anderen Aufgabe oder zu einem anderen Block navigieren, den Test pausieren oder den Test beenden. Mit der Beschreibung der ersten Gruppe, sollten nun auch alle andere Gruppe verständlich sein. 

:::

Die verfügbaren Attribute, die zugehörigen möglichen Attributwerte und in der Testtaker-XML und deren Bedeutung werden nachfolgend aufgelistet. Es wird auch aufgezeigt welchen Elementen Daten in Form von Text zugeordnet werden können. **Die Attribute, Werte und Daten werden dabei dem jeweiligen Xml-Element zugeordnet.**

::: {.callout-important}
Nicht alle Attributwerte eines Attributs sind frei wählbar. Bei einzelnen können nur vordefinierte Werte zugewiesen werden. Zum Beispiel kann das Attribut: `mode` im Element: `<Login>` nur einen definierten Wert erhalten. Dieser Wert ist einer entsprechenden Liste zu entnehmen. Hingegen ist der Wert des Attributs: `name` in `<Login>` frei wählbar. Auch Dateneingaben (Texteingaben) sind nicht immer frei wählbar. Bspw. können dem Element `<Booklet>` Daten hinzugefügt werden, die bestimmen welches Booklet aufgerufen wird. Hier muss natürlich die richtige ID des Booklets eingetragen werden, sonst wird das entsprechende Booklet nicht aufgerufen. 
:::

```{=html}
<table style="width:100%">
<tr>
    <td><code>Metadata</code></td>
    <td></td>
    <td></td>
    <td style="width:90%">Keine Attribute, keine Daten</td>
</tr>
<tr>
    <td><code>Describtion</code></td>
    <td>>xxx<</td>
    <td>Daten</td>
    <td>Text frei wählbar</td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td>id</td>
    <td>Attribut</td>
    <td>frei wählbarer Wert</td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td>label</td>
    <td>Attribut</td>
    <td>frei wählbarer Wert</td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td>validTo</td>
    <td>Attribut</td>
    <td>Bestimmt wie lange ein Zugang gültig ist. Frei wählbarer Wert im Format: dd/mm/yyyy hh:mm</td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td>validFrom</td>
    <td>Attribut</td>
    <td>Bestimmt ab wann ein Zugang gültig ist. Frei wählbarer Wert im Format: dd/mm/yyyy hh:mm</td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td>validFor</td>
    <td>Attribut</td>
    <td>Bestimmt einen Zeitraum für einen Zugang. Frei wählbarer Minutenwert im Format: Integer</td>
</tr>
<tr>
    <td><code>Login</code></td>
    <td>name</td>
    <td>Attribut</td>
    <td>Frei wählbarer Wert. Wird zur Anmeldung am Testcenter benötigt, um entsprechend des gewählten Testmodi einen Test durchzuführen.</td>
</tr>
<tr>
    <td><code>Login</code></td>
    <td>mode</td>
    <td>Attribut</td>
    <td>Vordefinierter Wert. Bestimmt wie ein Test ablaufen soll (finaler Test oder Probetest etc.). Weiteres ist den Referenzen: <b>Modi der Testdurchführung</b> zu entnehmen
    </td>
</tr>
<tr>
    <td><code>Login</code></td>
    <td>pw</td>
    <td>Attribut</td>
    <td>Frei wählbares Passwort. Wird zur Anmeldung am Testcenter benötigt, um entsprechend des gewählten Testmodi einen Test durchzuführen.</td>
</tr>
<tr>
    <td><code>Booklet</code></td>
     <td>code</td>
    <td>Attribut</td>
    <td>Frei wählbarer Wert. Die ID in der Booklet.xml muss den selben Namen tragen (Groß-/Kleinschreibung beachten!)</td>
</tr>
<tr>
    <td><code>Booklet</code></td>
    <td>>xxx<</td>
    <td>Daten</td>
    <td>Text sollte ID der Booklet-XML entsprechen</td>
</tr>
</table>
```

## Textersetzungen

Die Anwendung ermöglicht es zur Laufzeit Änderungen an Texten durchzuführen und somit individuelle Texte zu schaffen. Welche Textteile innerhalb der Anwendung ersetzt werden sollen, wird mit den Attributen des nachfolgenden Elements festgelegt.

```{=html}
<table>
<tr>
    <td><code>CustomText</code></td>
    <td>key</td>
    <td>Attribut</td>
    <td>Vordefinierter Wert. Erzeugt einen Custom Text. Siehe <b>Custom Text Configuration.</b></td>   
</tr>
<tr>
    <td><code>CustomText</code></td>
    <td>>xxx<</td>
    <td>Datum</td>
    <td>frei wählbar Text zur Anzeige eines Custom Text</td>
</tr>
</table>
```
::: {.callout-note}
Die Attributwerte für das Attribut `key` sind nicht frei wählbar. Es können nur Werte verwendet werden, die [**hier**](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/custom-texts.html) gelistet sind! Alle Texte, die nicht geändert werden, erhalten den Standardtext.
:::


# Einrichten der Testleitungskonsole

Der Gruppenmonitor kann in der Testtaker.xml über den Modus eingeschaltet werden. Es stehen zwei Modi dafür zur Verfügung: `monitor-group` und `monitor-study`. Im Modus: `monitor-group` können alle Logins der zugehörigen Gruppe gesteuert werden. Im Modus: `monitor-study` können alle Logins in allen Gruppen gesteuert werden