---
lang: de
title: "XML zur Studien-Definition (Testtaker-XML)"
---

Die Zugangsdaten für die teilnehmenden Testpersonen und weitere wichtige Funktionen für den Testablauf werden in einer XML-Datei festgelegt. Diese XML-Datei trägt IQB-intern den Namen: **Testtaker-XML**. Prinzipiell ist der Dateiname aber frei wählbar.
Folgende Funktionen erfüllt die Testtaker-XML:

* Festlegung Zugangsdaten/ Anmeldeverfahren:
* Gruppierung von Zugangsdaten
* Gruppenbeschränkungen
* Testheftzuweisungen
* Testablauf (Modi der Testdurchführung)
* **individuelle Textersetzungen**
* **Gruppenmonitoring**

::: {.callout-important}
Die in der XML-Datei angelegten Attribute und Elemente sind nicht frei wählbar, sondern orientieren sich an einer Schema-Definition. Diese gibt vor, welche Elemente und Attribute verwendet werden dürfen. Die Schema Definition für die Testtaker-XML ist [hier](https://github.com/iqb-berlin/testcenter/blob/master/definitions/vo_Testtakers.xsd) ersichtlich.
:::

::: {.callout-important}
Jede Versionsänderung des Testcenters kann auch Änderungen in der Schema-Definition enthalten. Es ist daher darauf zu achten, dass in der verwendeten Testtaker-XML auch die aktuelle zur Version passende Schema-Definition verwendet wird. Wird bspw. das Testcenter in Version 15.0.0 verwendet, sollte auch die Schema-Definition 15.0.0 verwendet werden. Beim Laden der Testtaker-XML in das Testcenter erzeugt dieses auch eine Warnung, wenn die verwendete Schema-Definition nicht zur Testcenterversion passt.
:::

Die Schema-Definition wird im Kopf der XML eingebunden. Hier auf eine Schema-Definition zur Testcenterversion 15.0.1:

```{.xml .code-overflow-wrap}
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.0.1/definitions/vo_Testtakers.xsd">

</Testtakers>
```
::: {.callout-tip collapse="true"}

## Ein Beispiel

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.0.1/definitions/vo_Testtakers.xsd">

<Metadata>
    <Description>
    This file contains some logins for testing and works a a sample for developers.
    </Description>
</Metadata>

<CustomTexts>
    <CustomText key="app_title">Hier steht ein Custom Text</CustomText>
</CustomTexts>

<Group id="sample_group" validFrom="1/3/2024 10:00" label="Primary Sample Group">
    <Login mode="run-hot-return" name="test" pw="user123">
        <Booklet codes="xxx">BOOKLET.SAMPLE-1</Booklet>
        <Booklet codes="yyy">BOOKLET.SAMPLE-3</Booklet>
    </Login>
    <Login mode="monitor-group" name="test-group-monitor" pw="user123"/>
</Group>

<Group id="study_group" label="A group for the study monitor">
    <!-- the study monitor has access to all other groups on the workspace -->
    <Login mode="monitor-study" name="test-study-monitor" pw="user123"/>
</Group>

<Group id="trial_group" label="A Group for Trials and Demos" validFor="45">
    <Login mode="run-trial" name="test-trial" pw="user123">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-demo" name="test-demo" pw="user123">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-simulation" name="test-simulation" pw="user123">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
</Group>

<Group id="passwordless_group" label="A group of persons without password">
    <Login mode="run-hot-restart" name="test-no-pw">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-trial" name="test-no-pw-trial">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
</Group>

<Group id="expired_group" validTo="1/3/2020 19:30" label="An already expired group">
    <Login mode="run-hot-restart" name="test-expired">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="monitor-group" name="expired-group-monitor" pw="user123"/>
    <Login mode="monitor-study" name="expired-study-monitor" pw="user123"/>
</Group>

<Group id="future_group" validFrom="26/3/2030 9:00" label="An not yet active group">
    <Login mode="run-hot-restart" name="test-future">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
</Group>

</Testtakers>
```

In diesem Beispiel sind 6 Gruppen zu finden. Diese Gruppen enthalten eine unterschiedliche Zahl von Logins, Anmeldeverfahren (mit Passwort, ohne Passwort etc.), Modi und zeitlichen Beschränkungen. 

In der ersten Gruppe: sample_group befinden sich 2 Logins. Die Gruppe verfügt über eine Zeitbeschränkung (`validFrom`). Alle dieser Gruppe zugehörigen Logins können sich erst am 01.03.2024 um 10:00 Uhr anmelden. Nach Anmeldung des ersten Logins am Testcenter, stehen je nach erfolgter Code-Eingabe 2 Testhefte zur Auswahl (BOOKLET.SAMPLE-1, BOOKLET.SAMPLE-3). Die Studie soll im Modus: run-hot-return durchgeführt werden, es werden also alle Antworten unter dem Gruppennamen: sample_group, dem Login: Test und dem entsprechenden Code gespeichert. Nach Anmeldung des zweiten Logins wird ein Gruppenmonitor präsentiert. Mit Hilfe dieses Monitor können die Aktivitäten innerhalb der Gruppe überwacht und gesteuert werden. Ist bspw. der erste Login aktiv, ist dies im Gruppenmonitor ersichtlich und die Testleitung kann die angemeldete Personen nun im Testheft zu einer anderen Aufgabe oder zu einem anderen Block navigieren, den Test pausieren oder den Test beenden. Mit der Beschreibung der ersten Gruppe, sollten nun auch alle andere Gruppe verständlich sein. 

:::

Die verfügbaren Attribute, die zugehörigen möglichen Attributwerte in der Testtaker-XML und deren Bedeutung werden nachfolgend aufgelistet. Es wird auch aufgezeigt, welchen Elementen Daten in Form von Text zugeordnet werden können. Nicht alle Attributwerte sind frei wählbar, manche müssen entsprechenden Vorgaben entsprechen. **Die Attribute, Werte und Daten sind in der nachfolgenden Liste bis in die zweite Rekursionsebene gelistet und beschrieben.**

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
<Testtakers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.0.1/definitions/vo_Testtakers.xsd">

<Metadata>
    <Description>
    This file contains some logins for testing and works a a sample for developers.
    </Description>
</Metadata>

<CustomTexts>
    <CustomText key="app_title">Hier steht ein Custom Text</CustomText>
</CustomTexts>

<Group id="trial_group" label="A Group for Trials and Demos" validFor="45">
    <Login mode="run-trial" name="test-trial" pw="erds#">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-demo" name="test-demo" pw="tzu#w">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-simulation" name="test-simulation" pw="er34#j">
        <Booklet>BOOKLET.SAMPLE-1</Booklet>
    </Login>
    <Login mode="run-hot-return" name="test-hot" pw="vg56t#">
        <Booklet codes="xxx">BOOKLET.SAMPLE-1</Booklet>
        <Booklet codes="yyy">BOOKLET.SAMPLE-3</Booklet>
    </Login>
</Group>

</Testtakers>
```

```{=html}
<table>
<tr>
    <th><b>Hauptelement</b></th>
    <th><b>Unterlement</b></th>
    <th><b>Attribut</b></th>
    <th><b>Datum</b></th>
    <th><b>Beschreibung</b></th>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>Metadata</code></td>
    <td></td>
    <td></td>
    <td>Keine Attribute, keine Daten</td>
</tr>
<tr>
    <td><code>Metadata</code></td>
    <td><code>Describtion</code></td>
    <td></td>
    <td>>abc<</td>
    <td>Text frei wählbar</td>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>CustomTexts</code></td>
    <td></td>
    <td></td>
    <td>Mehr Informationen dazu sind im Abschnitt: **Textersetzungen** zu finden.</td>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>Group</code></td>
    <td>id</td>
    <td></td>
    <td>frei wählbarer Wert</td>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>Group</code></td>
    <td>label</td>
    <td></td>
    <td>frei wählbarer Wert</td>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>Group</code></td>
    <td>validTo</td>
    <td></td>
    <td>Bestimmt wie lange ein Zugang gültig ist. Frei wählbarer Wert im Format: dd/mm/yyyy hh:mm</td>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>Group</code></td>
    <td>validFrom</td>
    <td></td>
    <td>Bestimmt ab wann ein Zugang gültig ist. Frei wählbarer Wert im Format: dd/mm/yyyy hh:mm</td>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>Group</code></td>
    <td>validFor</td>
    <td></td>
    <td>Bestimmt einen Zeitraum für einen Zugang. Frei wählbarer Minutenwert im Format: Integer</td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td><code>Login</code></td>
    <td>name</td>
    <td></td>
    <td>Frei wählbarer Wert. Wird zur Anmeldung am Testcenter benötigt, um entsprechend des gewählten Testmodi einen Test durchzuführen.</td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td><code>Login</code></td>
    <td>mode</td>
    <td></td>
    <td>Vordefinierter Wert. Bestimmt wie ein Test ablaufen soll (finaler Test oder Probetest etc.). Weiteres ist den Referenzen: <b>Modi der Testdurchführung</b> zu entnehmen
    </td>
</tr>
<tr>
    <td><code>Group</code></td>
    <td><code>Login</code></td>
    <td>pw</td>
    <td></td>
    <td>Frei wählbares Passwort. Wird zur Anmeldung am Testcenter benötigt, um entsprechend des gewählten Testmodi einen Test durchzuführen.</td>
</tr>
<tr>
    <td><code>Login</code></td>
    <td><code>Booklet</code></td>
    <td>code</td>
    <td></td>
    <td>Frei wählbarer Wert. Die ID in der Booklet.xml muss den selben Namen tragen (Groß-/Kleinschreibung beachten!)</td>
</tr>
<tr>
    <td><code>Login</code></td>
    <td><code>Booklet</code></td>
    <td></td>
    <td>>abc<</td>
    <td>Text sollte ID der Booklet-XML entsprechen</td>
</tr>
</table>
```
## Textersetzungen

Die Anwendung ermöglicht es zur Laufzeit Änderungen an Texten durchzuführen und somit individuelle Texte zu schaffen. Welche Textteile innerhalb der Anwendung ersetzt werden sollen, wird mit den Attributen des nachfolgenden Elements festgelegt.

```{.xml .code-overflow-wrap}
<Testtakers>

    <CustomTexts>
        <CustomText key="app_title">Hier steht ein Custom Text</CustomText>
    </CustomTexts>

</Testtakers>
```

```{=html}
<table>
<tr>
    <th><b>Hauptelement</b></th>
    <th><b>Unterelement</b></th>
    <th><b>Attribut</b></th>
    <th><b>Datum</b></th>
    <th><b>Beschreibung</b></th>
</tr>
<tr>
    <td><code>Testtakers</code></td>
    <td><code>CustomTexts</code></td>
    <td></td>
    <td></td>
    <td>Keine Daten, keine Attribute.</td>   
</tr>
<tr>
   <td><code>CustomTexts</code></td>
    <td><code>CustomText</code></td>
    <td>key</td>
    <td></td>
    <td>Vordefinierter Wert. Erzeugt einen Custom Text. Siehe <b>Custom Text Configuration.</b></td>   
</tr>
<tr>
    <td><code>CustomTexts</code></td>
    <td><code>CustomText</code></td>
    <td></td>
    <td>>abc<</td>
    <td>frei wählbar Text zur Anzeige eines Custom Text</td>
</tr>
</table>
```
::: {.callout-note}
Die Attributwerte für das Attribut `key` sind nicht frei wählbar. Es können nur Werte verwendet werden, die [**hier**](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/custom-texts.html) gelistet sind! Alle Texte, die nicht geändert werden, erhalten den Standardtext.
:::


## Gruppenmonitoring

Der Gruppenmonitor kann in der Testtaker.xml über den Modus eingeschaltet werden. Es stehen zwei Modi dafür zur Verfügung: `monitor-group` und `monitor-study`. Im Modus: `monitor-group` können alle Logins der zugehörigen Gruppe gesteuert werden. Im Modus: `monitor-study` können alle Logins in allen Gruppen gesteuert werden.

Hier ein Beispiel:

```{.xml .code-overflow-wrap}
<Testtakers>
    <Group id="sample_group" validFrom="1/3/2024 10:00" label="Primary Sample Group">
        <Login mode="run-hot-return" name="test">
            <Booklet codes="xxx">BOOKLET.SAMPLE-1</Booklet>
            <Booklet codes="yyy">BOOKLET.SAMPLE-3</Booklet>
        </Login>
        <Login mode="monitor-group" name="test-group-monitor" pw="er45tz"/>
    </Group>
</Testtakers>
```

In diesem Beispiel wird ein Gruppenmonitor für die Gruppe: **sample_group** angelegt. Nach der Anmeldung am Testcenter mit dem Namen: **test-group-monitor** und dem Passwort: **er45tz** können die beiden Testhefte: **BOOKLET.SAMPLE-1** und **BOOKLET.SAMPLE-3** zu Voransicht gestartet werden. Außerdem ist eine Schaltfläche zu sehen, die den Gruppenmonitor startet. Der Gruppenmonitor zeigt den Status der beiden angelegten Personen (Codes): **xxx** und **yyy** und die Testheftstrukturen der zugeordneten Testhefte: **BOOKLET.SAMPLE-1** und **BOOKLET.SAMPLE-3** an.