---
lang: de
title: "XML zur Testheft-Definition (Booklet-XML)"
---

##

Eine XML-Datei übernimmt die Testheft-Definition. Sie trägt IQB-intern den Namen **Booklet-XML**. Der Dateiname kann frei gewählt werden. Folgendes kann in dieser Datei festgelegt werden:

* Festlegung Reihenfolge Aufgaben
* **Testlet:** Aufgabenbündelung und Beschränkungen in Testlets
* **Testheft-Konfiguration:** Testverhalten, Testlayout, Testmethode

::: {.callout-tip collapse="true"}

## Ein einführendes Beispiel

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.0.1/definitions/vo_Booklet.xsd">
    <Metadata>
        <Id>BOOKLET.SAMPLE-1</Id>
        <Label>Sample booklet</Label>
        <Description>This a sample booklet for testing/development/showcase purposes.</Description>
    </Metadata>

    <BookletConfig>
        <Config key="unit_screenheader">WITH_BOOKLET_TITLE</Config>
        <Config key="page_navibuttons">SEPARATE_BOTTOM</Config>    
        <Config key="pagingMode">concat-scroll-snap</Config>
        <Config key="force_presentation_complete">ON</Config>
        <Config key="force_response_complete">ON</Config>
    </BookletConfig>

    <Units>

        <Unit id="UNIT.SAMPLE-1" label="A Sample Unit to demonstrate" labelshort="Sample Unit 1"/>

        <Testlet id="tslt1" label="First block with restrictions">
            <Restrictions>
                <CodeToEnter code="sample">Please insert the word `sample`.</CodeToEnter>
                <TimeMax minutes="10" />
                <DenyNavigationOnIncomplete presentation="OFF" response="OFF"/>	
            </Restrictions>
            <Unit id="UNIT.SAMPLE-2" label="A very Simple Sample Unit" labelshort="2nd Sample Unit"/>
        </Testlet>
    
        <Unit id="UNIT.SAMPLE-1" label="A Sample Unit to demonstrate" labelshort="Sample Unit 1" alias="an_alias"/>

        <Testlet id="tslt2" label="Second block without restrictions">
            <Unit id="UNIT.SAMPLE-3" label="Sample Unit again, with Alias" labelshort="Sample Unit Again"/>
        </Testlet>

    </Units>

</Booklet>
```
`Metadata`

In diesem Beispiel erhält das Testheft zuerst eine eindeutige Id: **BOOKLET.SAMPLE-1**. Mit Hilfe dieser Id kann das Testheft in der **Testtaker-XML** eingebunden und einer Testperson zugeordnet werden. Es folgt ein Label und eine Beschreibung, die frei wählbar sind. 

`BookletConfig`

Nachfolgend erfolgt die Booklet-Konfiguration. Hier gibt es eine Vielzahl von Konfigurationsmöglichkeiten. Exemplarisch sind an dieser Stelle einige aufgeführt. Welche Funktionalitäten die einzelnen Werte erfüllen, ist einer entsprechenden Liste zu entnehmen (Verweis im Abschnitt: Testheft-Konfigurationen). Bspw. würde mit dem Wert: `unit_screenheader` und dem Datum: **WITH_BOOKLET_TITLE** während der Testdurchführung das in diesem Beispiel angegebene Label angezeigt werden. 

`Units`

Hier erfolgt nun die Deklaration der während der Testdurchführung angezeigten Aufgaben. Hier wird zuerst eine einleitende Aufgabe mit der Id: **UNIT.SAMPLE-1** aufgerufen. Dieser wird ein entsprechendes Label zugewiesen und ein Short-Label. Letzteres kann bei entsprechender Testheft-Konfiguration in der Aufgaben-Navigationsleiste angezeigt werden.

Es folgt das erste Testlet (Block) mit Zugangsbeschränkungen, einer zeitlichen Beschränkung und einer Navigationsbeschränkung. Die in diesem Beispiel aufgeführte Navigationsbeschränkung `DenyNavigationOnIncomplete` überschreibt das Verhalten in der Testheft-Konfiguration, hier `force_presentation_complete` und `force_response_complete`nur für dieses Testlet. Für das nächste Testlet werden wieder die Werte aus der Testheft-Konfiguration verwendet. Nachfolgend wird eine Aufgabe: **UNIT.SAMPLE-2** in das Testlet eingebunden. Alle Aufgaben in diesem Testlet unterliegen den Beschränkungen des Testlets.

Auf das erste Testlet folgt eine weitere Aufgabe. Es fällt auf, dass diese Aufgabe die selbe Id trägt wie die erste Aufgabe, nämlich: **UNIT.SAMPLE-1**. Die Mehrfacheinbindung einer Aufgabe mit gleicher Id ist nicht erlaubt, das Testcenter würde hier bei der Testheft-Validierung eine entsprechende Fehlermeldung ausgeben. Manchmal kann es aber sinnvoll sein ein und die selbe Aufgabe mehrfach zu verwenden. Aus diesem Grund ist bei dieser Aufgabe ein zusätzliches Attribut: `alias` zu finden. Wird eine Aufgabe mit gleicher Id mehrfach in einem Testheft deklariert, kann mit Hilfe des Alias eine Unterscheidung der Aufgabe stattfinden und die Testcenter-Validierung schlägt nicht fehl.

Es folgt ein weiteres Testlet ohne Beschränkungen und mit nur einer einzigen Aufgabe.
:::

Die verfügbaren Attribute, die zugehörigen möglichen Attributwerte in der Booklet-XML und deren Bedeutung werden nachfolgend aufgelistet. Es wird auch aufgezeigt, welchen Elementen Daten zugeordnet werden können. **Die Attribute, Werte und Daten sind in der nachfolgenden Liste bis in die zweite Elementenebene gelistet und beschrieben.**

::: {.callout-important}
Die in der XML-Datei angelegten Attribute und Elemente sind nicht frei wählbar, sondern orientieren sich an einer Schema-Definition. Diese gibt vor, welche Elemente und Attribute verwendet werden dürfen. Die Schema Definition für die Booklet-XML befindet sich im Testcenter GitHub-Repository [**hier**](https://github.com/iqb-berlin/testcenter/blob/master/definitions/vo_Booklet.xsd).
:::

Die Schema-Definition wird im Kopf der XML eingebunden. Hier auf eine Schema-Definition zur Testcenterversion 15.0.1:

```{.xml .code-overflow-wrap}
<Booklet xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/iqb-berlin/testcenter/15.0.1/definitions/vo_Booklet.xsd">

</Booklet>
```

::: {.callout-important}
Jede Versionsänderung des Testcenters kann auch Änderungen in der Schema-Definition enthalten. Es ist daher darauf zu achten, dass in der verwendeten Booklet-XML auch die aktuelle zur Version passende Schema-Definition verwendet wird. Wird bspw. das Testcenter in Version 15.0.1 verwendet, sollte auch die Schema-Definition 15.0.1 verwendet werden. Beim Laden der Booklet-XML in das Testcenter erzeugt dieses auch eine Warnung, wenn die verwendete Schema-Definition nicht zur Testcenterversion passt.
:::

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
<Booklet>

    <Metadata>
        <Id>BOOKLET.SAMPLE-1</Id>
        <Label>Sample booklet</Label>
        <Description>This a sample booklet for testing/development/showcase purposes.</Description>
    </Metadata>

    <BookletConfig>
    </BookletConfig>

    <Units>

        <Unit id="UNIT.SAMPLE-1" label="A Sample Unit to demonstrate" labelshort="Sample Unit 1"/>

        <Testlet>
        </Testlet>
    
        <Unit id="UNIT.SAMPLE-3" label="A Sample Unit to demonstrate" labelshort="Sample Unit 3"/>

    </Units>

</Booklet>
```

```{=html}
<table>
<tr>
    <th><b>Hauptelement</b></th>
    <th><b>Unterelement</b></th>
    <th><b>Attribut</b></th>
    <th><b>Datum</b></th>
    <th><b>Beschreibung</b></th>
</tr>
<tr>
    <td><code>Booklet</code></td>
    <td><code>Metadata</code></td>
    <td></td>
    <td></td>
    <td>Keine Daten, keine Attribute</td>
</tr>
<tr>
    <td><code>Metadata</code></td>
    <td><code>id</code></td>
    <td></td>
    <td>>abc<</td>
    <td>Frei wählbarer Wert. Über diese Id kann das Booklet in der Testtaker-XML eingebunden werden.</td>
</tr>
<tr>
    <td><code>Metadata</code></td>
    <td><code>Label</code></td>
    <td></td>
    <td>>abc<</td>
    <td>Frei wählbarer Wert zur Bezeichnung des Booklets.</td>
</tr>
<tr>
    <td><code>Metadata</code></td>
    <td><code>Description</code></td>
    <td></td>
    <td>>abc<</td>
    <td>Frei wählbarer Wert zur weiteren Beschreibung dieses Booklets.</td>
</tr>
<tr>
    <td><code>Booklet</code></td>
    <td><code>BookletConfig</code></td>
    <td></td>
    <td></td>
    <td>Mehr dazu im Abschnitt: <b>Testheft-Konfiguration.</b></td>
</tr>
<tr>
    <td><code>Booklet</code></td>
    <td><code>Units</code></td>
    <td></td>
    <td></td>
    <td>Keine Daten, keine Attribute</td>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Unit</code></td>
    <td>id</td>
    <td></td>
    <td>Frei wählbarer Wert. Wert muss in gleicher Schreibweise auch in der entsprechenden Unit unter ID aufgeführt sein!</td>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Unit</code></td>
    <td>label</td>
    <td></td>
    <td>Frei wählbarer Wert zur Bezeichnung der Unit.</td>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Unit</code></td>
    <td>labelshort</td>
    <td></td>
    <td>Frei wählbarer Wert zur Bezeichnung der Navigationsleiste im Testcenter.</td>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Unit</code></td>
    <td>alias</td>
    <td></td>
    <td>Eindeutiger frei wählbarer Alias. Dieser ermöglicht eine Mehrfachverwendung von Units mit gleicher Id im Testheft.</td>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Testlet</code></td>
    <td></td>
    <td></td>
    <td>Mehr dazu im Abschnitt: <b>Testlet</b></td>
</tr>
</table>
```

## Testheft Konfiguration

::: {.callout-note}
In Bearbeitung THuste: to do

* Text zum adaptiven Testen
:::

::: {.callout-important}
Es ist möglich Testhefte individuell zu konfigurieren. Hierfür steht ein Attribut: `key` im Unterlement: `Config` zur Verfügung. Diesem Attribut können nur vordefinierte Werte und Daten zugewiesen. 
:::

#### [Link](https://pages.cms.hu-berlin.de/iqb/testcenter/pages/booklet-config.html) zur Liste möglicher Werte Testheftkonfiguration. <br>

Nachfolgend ein Codebeispiel mit einigen individuellen Konfigurationen:

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
<Booklet>

    <Metadata>
    </Metadata>

    <BookletConfig>
        <Config key="unit_screenheader">WITH_BOOKLET_TITLE</Config>
        <Config key="page_navibuttons">SEPARATE_BOTTOM</Config>    
        <Config key="pagingMode">concat-scroll-snap</Config>
        <Config key="force_presentation_complete">ON</Config>
        <Config key="force_response_complete">ON</Config>
    </BookletConfig>
    
    <Units>
    </Units>

</Booklet>

```

```{=html}
<table>
<tr>
    <th><b>Hauptelement</b></th>
    <th><b>Untereement</b></th>
    <th><b>Attribut</b></th>
    <th><b>Datum</b></th>
    <th><b>Beschreibung</b></th>
</tr>
<tr>
    <td><code>BookletConfig</code></td>
    <td><code>Config</code></td>
    <td>key</td>
    <td></td>
    <td>Vordefinierter Wert. Ermöglicht eine individuelle Testheft-Konfiguration. Die möglichen zu verwendenden Werte sind im nächsten Abschnitt zu finden.</td>
</tr>
<tr>
    <td><code>BookletConfig</code></td>
    <td><code>Config</code></td>
    <td></td>
    <td>>abc<</td>
    <td>Vordefinierter Wert. Die möglichen zu verwendenden Werte sind im nächsten Abschnitt zu finden.</td>
</tr>
</table>
```
::: {.callout-note}
Werden Attributswerte und Daten in der Testheft-Konfiguration nicht aufgeführt, wird das in der Liste aufgeführte Standarddatum verwendet. Wird bspw. **unit_screenheader** nicht aufgeführt, wird hierfür das Standarddatum: **EMPTY** angenommen, der Booklet Titel wird dann nicht mehr angezeigt.
:::

## Testlet (Block)

Ein Testlet ist eine Gruppe von Units mit gemeinsamen Restriktionen (falls gesetzt). Testlets können auch rekursiv geschachtelt werden. Die Testlets der obersten Ebene werden auch als Block bezeichnet.

Zeitbegrenzungen (Restrictions/TimeMax) in geschachtelten Testlets werden ignoriert, sofern diese ebenfalls eine Zeitbegrezung haben.

```{.xml .code-overflow-wrap}
<?xml version="1.0" encoding="utf-8"?>
<Booklet>
  <Metadata>
  </Metadata>

  <BookletConfig>
  </BookletConfig>

  <Units>

    <Unit id="UNIT.SAMPLE-1" label="A Sample Unit to demonstrate" labelshort="Sample Unit 1"/>

    <Testlet id="tslt1" label="First block with restrictions">
      <Restrictions>
        <CodeToEnter code="sample">Please insert the word `sample`.</CodeToEnter>
        <TimeMax minutes="10" />
      </Restrictions>
      <Unit id="UNIT.SAMPLE-2" label="A very Simple Sample Unit" labelshort="2nd Sample Unit"/>
    </Testlet>
    
    <Unit id="UNIT.SAMPLE-3" label="A Sample Unit to demonstrate" labelshort="Sample Unit 3"/>

  </Units>
</Booklet>

```
```{=html}
<table>
<tr>
    <th><b>Hauptelement</b></th>
    <th><b>Unterelement</b></th>
    <th><b>Attribut</b></th>
    <th><b>Datum</b></th>
    <th><b>Beschreibung</b></th>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Testlet</code></td>
    <td></td>
    <td></td>
    <td>Keine Daten, keine Attribute.</td>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Testlet</code></td>
    <td>id</td>
    <td></td>
    <td>Frei wählbarer Wert.</td>
</tr>
<tr>
    <td><code>Units</code></td>
    <td><code>Testlet</code></td>
    <td>label</td>
    <td></td>
    <td>Frei wählbarer Wert zur Bezeichnung des Testlets.</td>
</tr>
<tr>
    <td><code>Testlet</code></td>
    <td><code>Restrictions</code></td>
    <td></td>
    <td></td>
    <td>keine Daten, keine Attribute</td>
</tr>
<tr>
    <td><code>Restrictions</code></td>
    <td><code>CodeToEnter</code></td>
    <td>code</td>
    <td></td>
    <td>Zugangscode für das Testlet. Frei wählbarer Wert.</td>
</tr>
<tr>
    <td><code>Restrictions</code></td>
    <td><code>CodeToEnter</code></td>
    <td></td>
    <td>>abc<</td>
    <td>Frei wählbarer Text. Dieser Text wird bei der Codeaufforderung angezeigt.</td>
</tr>
<tr>
    <td><code>Restrictions</code></td>
    <td><code>TimeMax</code></td>
    <td>minutes</td>
    <td></td>
    <td>Frei wählbarer numerischer Wert.</td>
</tr>
<tr>
    <td><code>Restrictions</code></td>
    <td><code>DenyNavigationOnIncomplete</code></td>
    <td>presentation</td>
    <td></td>
    <td>Es können für das Testlet gesonderte Bedingungen bzgl. Aufgabennavigation festgelegt werden. Diese überschreiben, die in der <code>BookletConfig</Code> festgelegten Bedingungen zur  Aufgabennavigation. Mögliche Werte sind: ON/OFF/ALWAYS</td>
</tr>
<tr>
    <td><code>Restrictions</code></td>
    <td><code>DenyNavigationOnIncomplete</code></td>
    <td>response</td>
    <td></td>
    <td>Es können für das Testlet gesonderte Bedingungen bzgl. Aufgabennavigation festgelegt werden. Diese überschreiben, die in der <code>BookletConfig</Code> festgelegten Bedingungen zur  Aufgabennavigation. Mögliche Werte sind: ON/OFF/ALWAYS</td>
</tr>

</table>
```

