---
lang: de
title: Arbeitsbereiche
---

# Grundfunktionen

Zur Organisation von Tests, Befragungen und System-Checks stehen Arbeitsbereiche zur Verfügung. Systemadministrator\*innen legen diese an und vergeben entsprechende Zugriffsberechtigungen. Mehr zum Thema Zugriffsrechte ist [hier](../access-rights.qmd) zu finden. Die Benennung dieser Bereiche richtet sich günstigerweise nach dem Zweck der Studie.

Nach der Anmeldung präsentiert das System eine Liste aller Arbeitsbereiche, die für die Anmeldung freigegeben sind. Mit einem Klick auf den jeweiligen Arbeitsbereich wird dieser geöffnet. Zur Liste der Arbeitsbereiche kehrt man zurück, indem man auf das IQB-Logo (links oben) klickt.

**Der Arbeitsbereich bietet drei Grundfunktionen. Diese können mit einem Klick auf den entsprechenden Reiter ausgewählt werden:**

## Dateien

Hier können alle zu einem Test benötigten Dateien hochgeladen werden. Durch einen Klick auf eine bereits im System befindliche Datei, kann diese auch heruntergeladen werden. Die Dateien können einzeln oder verpackt in einem ZIP-Archiv geladen werden. Das Testcenter ordnet die geladenen Dateien anschließend bestimmten Gruppen zu. Diese sind:

* **Ressourcen:** <br>
Wie der Name schon sagt, werden hier Dateien gruppiert, die als Ressource zu einer Unit dienen. Das sind Unit-VOUD, Player-HTML, Unit-VOCS (Kodierung) und GeoGebra-Pakete (.itcr). 

* **Units:**<br>
Alle Dateien zur Unit-Definition (Unit-XML's).

* **Testhefte:**<br>
Alle Dateien zur Testheft-Definition (Booklet-XML's).

* **Teilnehmerlisten:**<br>
Alle Dateien mit den Zugangsdaten für die Testpersonen (Testtaker-XML's).

Die folgende Darstellung zeigt die Abhängigkeit der Dateien voneinander. Da das Testcenter diese Abhängigkeiten auf Gültigkeit prüft, müssen die Dateien in der dargestellten Reihenfolge in das Testcenter geladen werden (**von links nach rechts**). Sie können auch nur in der entgegengesetzten Reihenfolge gelöscht werden, um keine Inkonsistenzen zu erzeugen.

::: {#fig-dep}
```{mermaid}
flowchart LR
  B[Ressourcen] --> C[Units]
  C --> D[Booklets]
  D --> E[Testtakers]
```
Player sind abhängig von Basis-Pakete für Player, Units sind abhängig von Player etc.
:::

Wird die Reihenfolge nicht beachtet, wird eine Fehlermeldung generiert und die entsprechende Datei wird nicht final geladen. Es ist so bspw. nicht möglich eine Booklet-XML zu laden, wenn die darin deklarierten Unit-XML's noch nicht im Testcenter sind. In diesem Fall, müssen zuerst die Unit-XML's und anschließend die Booklet-XML geladen werden. 

#### Überschreiben einzelner Dateien

Sollen Änderungen einer Datei in das Testcenter geladen werden, müssen die veralteten Dateien und die davon abhängigen Dateien nicht zwingend zuvor gelöscht werden. Es besteht auch die Möglichkeit einzelne Dateien zu überschreiben. Das vereinfacht und beschleunigt den Ladevorgang der Testinhalte. Damit eine Datei überschrieben werden kann, müssen die folgenden Bedingungen für die jeweilige Datei erfüllt sein:

* **Testtaker-XML**: Dateiname muss identisch mit dem Dateinamen der bereits im Testcenter befindlichen Testtaker-XML.
* **Booklet-XML**:Dateiname und Booklet-ID müssen identisch mit der bereits im Testcenter befindlichen Booklet-XML sein.
* **Unit-XML**: Dateiname und Unit-ID müssen identisch mit der bereits im Testcenter befindlichen Unit-XML sein.
* **VOUD-, VOCS- und Player-Dateien**: Dateiname muss identisch mit den bereits im Testcenter befindlichen Dateien sein.

## System-Check-Berichte

Wurde ein System-Check durchgeführt, können hier die erzeugten System-Check-Berichte heruntergeladen werden.

## Ergebnisse/Antworten

Wurde eine Studie in einem Hot-Modus durchgeführt, können hier Antworten und Logs heruntergeladen werden. Wurde eine Studie in einem Review-Modus durchgeführt, können an dieser Stelle Kommentare heruntergeladen werden. Ein Login zu einer Testung wird in einer der Testdateien (Testtaker-XML) angelegt. Jeder Login muss einer Gruppe zugeordnet werden. Der Datensatz wird nach der jeweiligen Gruppe sortiert angezeigt. Mehr zu den Testdateien ist im Kapitel: **Testinhalte** zu finden.

::: {.callout-note}
Werden die Antwortdaten einer Gruppe gelöscht, wird der Studienstand dieser Gruppe in den ursprünglichen Zustand versetzt. Mit dem Löschen dieses Datensatzes werden alle gegebenen Antworten gelöscht. Die Studie kann dann ein weiteres Mal zustandsbereinigt für die Logins der gelöschten Gruppe durchgeführt werden.
:::

## Tests löschen

Im zuvor beschriebenen Reiter kann der gesamte Antwortdatensatz einer Gruppe gelöscht werden. Sollen nur die gegebenen Antworten eines bestimmten Logins einer Gruppe gelöscht werden, ist das an dieser Stelle möglich.


