---
lang: de
title: "Häufig gestellte Fragen"
---

### Wie kann ich auf das Testcenter zugreifen?

Der Zugriff erfolgt mittels Adresseingabe in Ihrem Webbrowser. Beachten Sie bitte: Das Testcenter muss zuvor in Ihrer IT-Netzstruktur auf einem dafür geeignetem Server installiert werden. Die Serveradresse erhalten Sie dann von Ihrem IT-Dienstleister oder den internen Administrator\*innen.

### Welchen Browser sollte ich verwenden?

Es gibt da derzeitig keine Vorgaben seitens des IQB. Empfohlen werden die gängigen Browser, wie Google Chrome oder Firefox. **Mehr Information zu den Anforderungen an die Browser sind [hier](/Testcenter/intro.qmd) zu finden.**

### Wie wird das Testcenter installiert?

Mehr Informationen sind zu finden im Kapitel: Testcenter/Installation

### Ist es möglich im Vorfeld die Eignung der Geräte für eine Studiendurchführung zu testen?

Das Testcenter bietet einen sogenannten **System-Check** an. Dieser kann im Vorfeld auf dem Zielsystem ausgeführt werden. Mehr Informationen dazu sind im Kapitel: Testcenter/System-Check zu finden.

### Wie melde ich mich am Testcenter an?

Eingabe der Testcenter-Serveradresse in einen Browser. Die Anmeldung erfolgt dann via Benutzernamen und Passwort. Die Zugangsdaten werden von entsprechend berechtigten Personen (SuperAdmin) im Testcenter eingerichtet.

### Warum kann ich mich trotz vorhandener Zugangsdaten nicht anmelden?

Die Anmeldung für Administrator\*innen erfolgt nach Eingabe der Zugangsdaten mit dem Schalter: **Weiter als Admin**. Die Anmeldung für Testpersonen erfolgt mit dem Schalter: **Weiter**.

### Warum sehe ich nach der Anmeldung keine Inhalte im Testcenter?

Eventuell sind keine Inhalte zu sehen, weil die Administrator\*innen keine Arbeitsbereiche für Sie freigegeben haben. Wenden Sie sich dazu bitte an die Administrator\*innen.

### Wie lade ich Inhalte in meinen Arbeitsbereich?

Öffnen Sie Ihren Bereich, wechseln Sie zum Tab: **Dateien** und klicken Sie auf die kleine Wolke im rechten Bereich des Fensters.

### Warum werden GeoGebra-Elemente nicht angezeigt?

Eventuell wurde das für GeoGebra benötigte Paket noch nicht in den Arbeitsbereich der durchzuführenden Studie geladen. Mehr dazu finden Sie im Kapitel: Testcenter/Daten und Prozesse.

### Warum werden meine Testdateien beim Laden in das Testcenter abgelehnt?

Hier kann es verschiedene Gründe geben. Vielleicht wurden die Daten in der falschen Reihenfolge geladen oder es fehlen abhängige Dateien. **Mehr dazu ist dem Kapitel: Testcenter/Daten und Prozesse/Daten Upload.**

### Warum werden beim Laden manche Dateien mit einem orangefarbenen Dreieck versehen?

Es gibt hier eventuell mehrere Ursachen:

* Es erscheint ein orangefarbenes Dreieck mit dem Vermerk: File has no link to XSD-Schema.
   * In Ihrer Testdatei ist kein Verweis auf die zugehörige Schema-Definition gesetzt.

* Es erscheint ein orangefarbenes Dreieck mit dem Vermerk: .....never used
   * Ihre Testdatei wird noch von keiner anderen Testdatei aufgerufen bzw. eingebunden.

### Wie bearbeite ich meine Testdateien?

Da es sich bei den Testdateien um XML-Dateien handelt, empfiehlt sich ein Editor der eine Hervorhebung der XML-Syntax ermöglicht. Generell ist aber eine Bearbeitung mit jedem Texteditor möglich.

### Wie werden meine Änderungen an einer der Testdateien wirksam?

Nach Speicherung der Änderungen, muss die geänderte Datei erneut in das Testcenter geladen werden.

### Wie starte ich meinen angelegten Test und gibt es eine Art Voransicht?

Die Zugangsdaten der Testpersonen werden in der XML zur Studien-Definition festgelegt. Diese XML muss mit allen anderen Testdateien in das Testcenter geladen werden. Nach Abmeldung kann sich dann eine Testperson mit den festgelegten Zugangsdaten und dem Schalter: "Weiter" anmelden. In der XML zur Studien-Definition wird außer den Zugangsdaten noch der Modus der Testdurchführung festgelegt. Mithilfe dieses Modus kann festgelegt werden, ob der Test "heiß" ablaufen soll (run-hot-restart und run-hot-return) oder in einer Art Vorschau (run-review).

### Das Booklet kann bei einer Testdurchführung nicht geöffnet werden, es erscheint die folgende Meldung: *root element to Booklet should be: booklet*

Eventuell ist die verwendete Testheft-XML beschädigt oder beinhaltet ein sogenanntes BOM (byte order mark). Dieses BOM kann weitere Metadaten zu der Datei enthalten. Ist ein solches BOM in der Testheft-XML angelegt, erscheint diese Fehlermeldung im Testcenter, da das BOM nicht gelesen werden kann. Außerdem kann die Datei beschädigt sein, weil sie bspw. mit Word oder einem anderen nicht geeigneten Instrument verändert wurde. Verwenden Sie für die Bearbeitung der XML-Datei nur geeignete Editoren wie bspw. Notepad++. Arbeiten Sie bereits mit einem geeigneten Editor, achten Sie auf die Einstellungen zur Zeichenkodierung. Hier darf die Option: UTF-8-BOM nicht aktiv sein.

### Kann ich den Test überwachen oder steuern?

Das Testcenter stellt hierfür den **Gruppenmonitor** zur Verfügung. **Mehr dazu kann den Kapiteln: Testcenter/Gruppenmonitor entnommen werden.**

### Warum stimmt die Reihenfolge meiner Aufgabe nicht?

Die Reihenfolge der Aufgaben wird in der XMl zur Testheft-Definition festgelegt. Die Wiedergabe entspricht der hier angelegten Aufgaben von oben nach unten.

### Audios können nicht gestartet werden. Der Play-Knopf ist inaktiv.

Das Audio darf nicht Mono sein, sollte eine feste Bitrate aufweisen und muss im MP3-Format vorliegen.

### Warum werden Aufgabeninhalte in Chrome nur kurz angezeigt?

Bitte prüfen Sie, ob für Chrome eine Erweiterung mit dem Namen "Urban VPN proxy Unblocker" installiert ist. Falls ja, deinstallieren Sie diese Erweiterung probeweise.

### Wie kann ich den Test auswerten? Wo finde ich die Daten?

Das Testcenter speichert in bestimmten **Testmodi** die Ergebnisse eines Tests in dem Arbeitsbereich ab, in welchem sich auch die Testdateien für den Test befinden. Öffnen Sie den jeweiligen Arbeitsbereich und klicken Sie auf den Reiter: **Ergebnisse/Antworten**. Dort können Sie die Ergebnisse herunterladen. Die Dateien werden dann in einem CSV-Format gespeichert.



