---
lang: de
title: "Format Base64"
---

Bei dem Format [Base64](https://de.wikipedia.org/wiki/Base64) handelt es sich um Mediendateien (Audio, Video, Bilder), das von allen Betriebssystemen gleichermaßen verstanden wird. Es findet daher im Web-Bereich Anwendung. Die Player des IQB verwenden dieses Format, um binäre Daten in JSON-Dateien zu speichern. Dadurch vermeidet man externe Bezüge und kann Unit-Definitionen kompakt schreiben.

Normalerweise übernehmen die Editoren des IQB die Transformation einer Medien-Datei über Dialog. Man wählt eine Datei auf dem Computer, und der Editor wandelt diese Datei in das Base64-Format um. Wenn aber -- z. B. in einer frühen Entwicklungsphase eines Players -- manuell diese Konvertierung erfolgen muss, dann kann folgende Programmierung als Hilfe unter dem Windows-Betriebssystem benutzen.

# iqb-base64-generator

Als erster Schritt muss das Script heruntergeladen werden:

{::: {.callout-tip}
## Download

Das Script kann [hier heruntergeladen](https://github.com/iqb-berlin/base64-generator/releases/latest) werden.
:::}

