---
lang: de
title: "Aufgaben gestalten"
---

::: {.callout-note}
Alle Inhalte dieses Kapitels beziehen sich auf die Verwendung des Aspect-Editors. Informationen zu weiteren Editoren sind diesem [Kapitel](/tasks/) zu entnehmen.
:::

Der Aspect-Editor wird als Modul in das Studio geladen und kann anschließend in den Eigenschaften einer Aufgabe als zu verwendender Editor angegeben werden. Ist eine Aufgabe angewählt, kann der Editor mit Hilfe des Reiters: **Editor** geöffnet werden.

Der Editor bietet zwei Modi, den Standardmodus und den erweiterten Modus.

**Standardmodus:**
Im Standardmodus soll der größte Teil der Aufgaben angelegt werden. 
Er enthält daher nur die Assistenten, die Medienelemente „Text“, „Bild“, „Audio“ und „Video“, sowie die Spezialelemente „Lückentext“ und „Tabelle“. Alle diese Elemente haben schon die richtigen Voreinstellungen und müssen daher für die Standardformate nur inhaltlich angepasst werden.
Außerdem sind die Einstellungsmöglichkeiten rechts für alle Elemente, sowie die Abschnittseinstellungen an den einzelnen Abschnitten stark eingeschränkt. 

**Erweiterter Modus:**
Der erweiterte Modus ist nur in bestimmten Bereichen freigeschaltet und dient zum Anlegen von spezielleren und experimentellen Formaten, die nicht mithilfe der Assistenten angelegt werden können. Im Gegensatz zu den Standardformaten sind diese Formate nicht durch die Assistenten vorformatiert. Beim Anlegen können die prototypischen Aufgaben zur Hilfe gezogen werden.
In diesen Bereichen kann rechts oben im Editor zwischen Standardmodus und erweitertem Modus gewechselt werden.
