---
lang: de
title: "Lesestimulus-Email-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

Der Assistent „Stimulus: Lesestimulus – E-Mail“ hilft Ihnen beim Erstellen von Lesestimuli in Form einer E-Mail.

Nachdem Sie die Sprache der E-Mail Vorlage ausgewählt haben, erstellt der Assistent einen E-Mail Platzhalter. Anschließend können Sie auf die Platzhaltefelder doppelklicken und die Texte bearbeiten.

## Sprache

Im Assistenten können Sie zwischen den Vorlagen Deutsch, Englisch und Französisch wählen. 

## Instruktion

Nachdem Sie auf das Instruktionsfeld doppelgeklickt haben, öffnet sich ein Textbearbeitungsfeld und Sie können die Instruktion anpassen. Analog dazu können Sie Absender*in, Empfänger*in, Betreff, Datum und Uhrzeit, das Nachrichten- sowie das Quellenfeld bearbeiten.

## Bestätigen/Abbrechen

Nach allen gewünschten Einstellungen wird der Textabschnitt durch einen Klick auf „Bestätigen“ generiert, der Assistent wird automatisch geschlossen. Um Ihre Eingaben zu verwerfen, klicken Sie auf Abbrechen. Achtung: In diesem Fall gehen sämtliche Angaben verloren und Sie müssten erneut von vorne beginnen.
