---
lang: de
title: "Audiostimulus- Instruktion und Hörtext in einem Audio-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

# Instruktion und Hörtext in einem Audio

Der Assistent „Stimulus: Audiostimulus – Instruktion und Hörtext in einem Audio“ unterstützt Sie dabei, eine Aufgabe mit einem einzelnen Audiostimulus zu erstellen.
 
Dieser Assistent ist für Aufgaben gedacht, bei denen sich **Instruktion und Hörtext** in einer Datei befinden. Sie laden im Assistenten das Audio hoch und geben ggf. die Quelle an. 

## Audio
 
Klicken Sie auf den blauen Knopf, um ein Fenster zu öffnen, in dem die gewünschte Datei ausgewählt und mit „Öffnen“ ins IQB-Studio geladen werden kann.
Wenn Sie das Audio mehrfach abspielen möchten, können Sie das unter „maximale Abspielhäufigkeit“ für dieses Audio einstellen. 

::: {.callout-note}
Sollte die Einstellung mehr als 1 betragen, wird innerhalb des Audioelements eine Anzeige mit der bisherigen Anzahl der Audiostarts im Verhältnis zu den maximal verfügbaren Audiostarts generiert.
:::

## Quelle

Im unteren Eingabefeld fügen Sie die Quelle ein.
 
::: {.callout-note}
Der bei der Aufgabenerstellung automatisch generierte Text „Drücke zuerst auf das Dreieck, dann startet der Hörtext.“ kann nachträglich in den Texteigenschaften angepasst werden. 
:::

## Bestätigen/Abbrechen

Wenn Sie mit allen Eingaben zufrieden sind, klicken Sie auf „Bestätigen“ und der Assistent erstellt die Aufgabe im Studio für Sie. Um Ihre Eingaben zu verwerfen, klicken Sie auf Abbrechen. Achtung: In diesem Fall gehen sämtliche Angaben verloren und Sie müssten erneut von vorne beginnen.