---
lang: de
title: "Studie vorbereiten"
---

Es kann sehr schwierig sein nachträglich Änderungen an einer Studie vorzunehmen. Eine Studie sollte deshalb im Vorfeld gut durchdacht und geplant sein. Das IQB möchte an dieser Stelle Erfahrungen aus dem Praxisalltag einbringen und bewehrte Wege hin zu einem gesicherten Studienablauf aufzeigen. Dazu dienen die nachfolgend genannten Fragen, die sich die Studienleitung im Vorfeld einer Studie stellen sollte. Unter der Frage befinden sich Verweise auf Seite, die bei der Beantwortung einer Frage helfen können.

## Bietet der Server, auf dem das Testcenter installieren ist, ausreichende Performance für die geplante Studie?

Hier kann ein Lasttest hilfreich sein. Dieser wird im Kapitel **System-Setup** beschrieben. Dieses Kapitel ist eher für technisch versierte Personen, wie bspw. Server Administrator\*innen, gedacht.

## Verhält sich die installierte Variante des Testcenters richtig?

Vor jeder Veröffentlichung einer Testcenter-Version werden interne Testungen der Version durchgeführt. Dazu gehören E2E- und Unit-Tests. Um sicherzustellen, dass bei der eigenen Installation keine Probleme aufgetreten sind, kann vorab noch einmal eine E2E-Testung durchgeführt werden. Wie E2E-Test gestartet werden können, ist im Kapitel **System-Setup** beschrieben. Dieses Kapitel ist eher für technisch versierte Personen, wie bspw. Server Administrator\*innen, gedacht.

## Welche Endgeräte (Betriebssysteme, Browser etc.) kommen während der Studiendurchführung zum Einsatz? Ist die Internetanbindung ausreichend?

Ermittlung von OS- und Browserversionen, Gerätetyp und Internetanbindung:

* [System-Check](../preparation/system-check/)

Kommen Geräte zum Einsatz, die ab und an Probleme verursachen:

* [Endgeräte](../preparation/devices/index.qmd)

## Erfüllen alle Endgeräte die Anforderungen? Wie groß sind die verwendeten Testhefte?

* [Anforderungen](../preparation/require.qmd)

## Prüfen der Aufgaben

Wenn im Nachhinein Aufgaben angepasst werden müssen, kann das mühselig sein. Es wird daher empfohlen alle Aufgaben hinsichtlich Darstellung und Funktion ausreichend zu prüfen. Bereits während der Entwurfsphase im Studio können entsprechende Vorschauschleifen im Team der Aufgabenentwickler\*innen stattfinden. Mehr dazu ist dem Kapitel: **Aufgaben entwickeln** zu entnehmen. Auch im Testcenter gibt es die Möglichkeit die Aufgaben einem breiten Personenkreis zugänglich zu machen und Rückmeldungen einzusammeln, die zur Optimierung einer Aufgabe genutzt werden können. Hierfür steht der Modus: **run-review** zur Verfügung. In diesem Modus können Kommentare zu jeder Aufgabe gespeichert werden. Die Kommentare können dann von den Aufgabenwickler\*innen zur Optimierung genutzt werden.

## Ist die Studienkonfiguration durchdacht und erprobt?

* [Studienkonfiguration](../preparation/study-config/index.qmd)

## Organisatorisches

Die Beteiligten brauchen rechtzeitig klare Anweisungen, wie die Studie vorbereitet, durchgeführt und ausgewertet wird. Hierzu sind zunächst eine Reihe von Fragen zu beantworten und ggf. bestimmte Schritte vorzuziehen. Mitunter müssen die Festlegungen in Dokumenten festgehalten und verschickt werden: allg. Handreichungen, Manual für die Testleitung, Anträge beim Datenschutz, Elternanschreiben, Zugangsdaten für die Testpersonen usw..

Welche Zusatzmaterialien werden vor Ort benötigt: Taschenrechner, Lineal, Notizpapier, Kopfhörer?

Soll es eine Hotline geben? Für welchen Zeitraum?

Wie hoch ist das Risiko für technische Probleme? Soll jemand aus der Systemadministration oder Programmierung ständig greifbar sein?