---
lang: de
title: "Systemanforderung"
---

::: {.callout-important}
Werden die Systemanforderungen nicht erfüllt, ist eine Studien unter Umständen nicht durchführbar.
:::

## Browser

Darstellung und Verhalten einer Studie sind maßgeblich vom verwendeten Browser abhängig. Es gibt immer wieder die Diskussion darüber, ob bzw. in welchem Maße ältere Browser bzw. Browserversionen unterstützt werden sollen. Hier wird argumentiert, dass Schulen bzw. deren Träger oft nicht in der Lage seien, die Verwendung aktueller Browser sicherzustellen. Aus dieser Realität ergebe sich, dass die Programmierungen für TBA stets ein Maximum an Abdeckung auch für alte Browser leisten müssten.

Das IQB folgt hier jedoch den Anforderungen an die Datensicherheit, so wie es z. B. das [Bundesamt für Sicherheit in der Informationstechnik](https://www.bsi.bund.de/) formuliert:

> "Der Internet-Browser ist die zentrale Komponente für die Nutzung von Online-Angeboten und stellt somit eins der beliebtesten Ziele für Cyber-Angriffe dar. Hieraus ergibt sich ein besonders hohes Gefahrenpotenzial." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/Der-Browser/der-browser_node.html)

> "Installieren Sie alle Aktualisierungen sofort oder zeitnah nach ihrer Veröffentlichung, sowohl die für Ihren Browser, als auch für alle Erweiterungen und natürlich Ihr Betriebssystem. Verwenden Sie stets die neuste Version Ihres Browsers." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/updates-browser-open-source-software_node.html)

**Das IQB unterstützt daher nur die jeweils letzten beiden Hauptversionen eines Browsers bzw. die Versionen der letzten 12 Monate.**

Sollten ältere Versionen zum Einsatz kommen, empfiehlt sich eine Voransicht der Aufgaben mit der entsprechenden Browserversion. Hierfür bietet das Testcenter spezielle Modi der Studiendurchführung an, wie bspw. einen Review-Mode. Es kann auch der **System-Check** dafür genutzt werden. Hier können Aufgaben eingebunden werden, die während des System-Checks angezeigt werden. Zum Abschluss des System-Checks können dann Fragen zur Aufgabenansicht gestellt werden. Bspw. könnte gefragt werden, ob ein Audio/Video abgespielt werden konnte. Nach Auswertung des System-Checks, kann dann eine Aussage darüber getroffen werden, ob die Aufgaben mit den verwendeten Browserversionen richtig funktionieren.

::: {.callout-important}
Es gibt abenteuerliche Erweiterungen für Browser (Plugins), die mehr Sicherheit, bessere Performance, weniger Werbung, mehr Privatsphäre usw. versprechen. Oft greifen diese Erweiterungen aber massiv in die Kommunikation des Browsers mit dem Server ein und verfälschen Daten. Bei Problemen sollte man also diese Add-Ons usw. zumindest zeitweise deaktivieren.
:::

## Internetanbindung

Ist die Anbindung zu schlecht, kann im schlimmsten Fall die Studie im örtlichen Umfeld nicht durchgeführt werden. Leider kann an dieser Stelle keine generelle Aussage getroffen werden, ab welchen Werten eine Studie gesichert durchgeführt werden kann. Zur individuellen Bewertung einer Internetverbindung kann ein System-Check durchgeführt werden. Dieser kann so konfiguriert werden, dass eine Bewertung der Internetgeschwindigkeit bezogen auf die verwendete Testheftgröße erfolgen kann. Mehr dazu ist dem Kapitel: **System-Check** zu entnehmen.

::: {.callout-tip}
Ist die Internetanbindung nicht ausreichend, kann das Testcenter auch offline betrieben werden. Hierfür wird das Testcenter auf einem PC installiert und die entsprechenden Endgeräte werden mit diesem verbunden. Der PC fungiert dann als Server. 
:::

## IT Sicherheitsstrukturen

Manche IT-Sicherheitskonzepte in den Einrichtungen können die Studiendurchführung stören oder gänzlich unmöglich machen. Daher ist es wichtig zuvor die Erreichbarkeit des Testcenters aus dem Netz der Einrichtung heraus zu prüfen. 

## Lastverhalten Testcenter Server

Entscheidend für die Durchführbarkeit einer Studie ist die Belastbarkeit des Servers auf dem das Testcenter läuft. Das Lastverhalten kann mit einem Lasttest ermittelt werden. Entscheidend ist hierbei bereits vor Studienstart die Anzahl der Teilnehmer\*innen zu kennen. Mehr dazu ist dem Kapitel: **Installation / Lastverhalten** zu entnehmen.

## Testheftgrößen

Es kann nicht sichergestellt werden, dass die verfügbare Internetverbindung während einer Studiendurchführung stabil und zuverlässig hohe Downloadraten liefert. Es sollte ehr mit dem Gegenteil gerechnet werden. Um unter diesen Voraussetzung eine Studie stabil durchführen zu können, sind die Größen der zu ladenden Testhefte entscheidend. Bereits bei der Aufgabenentwicklung muss daher darauf geachtet werden, die Inhalte so klein wie möglich zu halten. Es kann an dieser Stelle leider keine Angabe zur max. Größe eines Testheftes gemacht werden. Der Grundsatz bei der Aufgabenentwicklung und auch bei der Aufgabenverteilung auf Testhefte, sollte immer lauten: So klein wie möglich. Getreu dieses Grundsatzes, muss die Notwendigkeit audiovisuelle Medien einzusetzen, stets hinterfragt werden und wenn möglich durch Alternativen ersetzt werden. Sind solche Medien unverzichtbar, sollte auf eine ausreichende Komprimierung geachtet werden. Mehr dazu ist dem nachfolgenden Kapitel zu entnehmen. 

::: {.callout-tip}
Informationen zur Ermittlung der Testheftgröße sind in den FAQ's zu finden. Hierfür gibt es den Punkt: "Wie groß ist mein Testheft?"
:::
---



