---
lang: de
title: "Audio"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

## Audioelemente

Das Medium „Audioelemente“ ermöglicht es, Audiodateien ins IQB-Studio zu laden.

Mit einem Klick auf das Element „Audio“ der Elementengruppe „Medium“ öffnet sich ein Fenster, in dem Sie die gewünschte Datei auswählen und durch einen Klick auf „Öffnen“ im IQB-Studio hochladen können. Im rechten Reiter „Eigenschaften“ können Sie Anpassungen im Audioelement vornehmen. 

::: {.callout-note}
Der Aufforderungstext „Bitte starten.“ inklusive roter Umrahmung des Fortschrittbalkens des Audios erscheint automatisch, sofern das Audio fünf Sekunden nach Betreten der Seite nicht gestartet wurde. 
:::

## Anpassen eines Audioelements
 
Neben der Anpassung der ID (hier: „audio_1“) können Sie mit einem Klick auf den blauen Knopf die Audiodatei ändern. Es öffnet sich ein Fenster, in dem Sie die gewünschte Datei auswählen und mit „Öffnen“ ins IQB-Studio laden können.