---
lang: de
title: "Lesestimulus Mobiltelefon-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

# Assistent: Lesestimulus Mobiltelefon

Der Assistent „Stimulus: Lesestimulus – Mobiltelefon“ hilft Ihnen beim Erstellen von Lesestimuli in Form von Textnachrichten auf einem Mobiltelefon. 

Im Assistenten können Sie zwischen der Vorlage auf Deutsch, Englisch oder Französisch wählen. Um Ihre Eingaben zu verwerfen, klicken Sie auf Abbrechen. 
Nachdem Sie Ihre Auswahl bestätigt haben, erstellt der Assistent einen Mobiltelefon Platzhalter. Anschließend können Sie auf die Platzhaltefelder doppelklicken und die Texte bearbeiten.

## Instruktion
 
Nachdem Sie auf das Instruktionsfeld doppelgeklickt haben, öffnet sich ein Textbearbeitungsfeld und Sie können die Instruktion anpassen. Analog dazu können Sie das Absender*innenfeld, das Nachrichtenfeld sowie das Quellenfeld bearbeiten. 
Weitere Details dazu finden Sie hier: [Editor](../../Medienelemente/Text/index.qmd)

## Bild
 
Sie können das Profilbild ändern, indem Sie das Bild anklicken und auf der rechten Seite auf den blauen Kreis „Medienquelle ändern“ klicken. Anschließend öffnet sich ein Fenster Ihres Computers und Sie können eine eigene Bilddatei auswählen.

## Farbe
 
Um die Hintergrundfarbe des Handys und des Displays zu ändern, müssen Sie zuerst den passenden Rahmen auswählen. Dazu klicken Sie auf den obersten pinken Knopf „Elementliste“.

::: {.callout-note}
Die ID des Rahmens kann gegebenenfalls abweichen, insbesondere wenn andere Aufgaben im Rahmen vorkommen.
::: 

Es öffnen sich alle aufgabenbezogenen Elemente. Wählen Sie per Klick „frame_1“ für die Handyhintergrundfarbe und „frame_2“ für die Displayfarbe aus.

Um die Farbe des Rahmens anzupassen, klicken Sie rechts im Reiter „Eigenschaften“ auf den Stift neben der Hintergrundfarbe. Hier im Beispiel ist der Rahmen des Handys ausgewählt.

Es öffnet sich ein Fenster, in dem Sie die neue Hintergrundfarbe auswählen können. Zur Bestätigung drücken Sie „OK“. Wenn Sie keine neue Hintergrundfarbe auswählen möchten, klicken Sie auf „Abbrechen“.

Möchten Sie die Farbe des Displays ändern, wählen Sie den passenden Rahmen „frame_2“ aus und gehen im nächsten Schritt wie bei Änderung der Handyfarbe vor. 
