---
lang: de
title: "Stimulus-Text-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

Der Assistent „Stimulus: Lesestimulus – Text“ hilft Ihnen beim Erstellen von Aufgabentexten. Diese können hier formatiert werden. 

Wählen Sie dazu beim Assistenten „Stimulus: Lesestimulus – Text“

Dann öffnet sich dieses Textbearbeitungsfeld. 

Sie können nun den Text einfügen, den*die Autor*in vermerken und die Überschrift bearbeiten. 

::: {.callout-tip}

Die Schriftart ist aus Gründen der Vereinheitlichung voreingestellt und kann nicht verändert werden. 
:::

Weitere Formatierungsmöglichkeiten können Sie unter Schriftausrichtung, Schrift, Absatz, Listen, Textausrichtung, Einrückung, Bild und Sonderelemente vornehmen. 
Die Fußnote kann auch beim Platzhalter „Fußnoten“ eingefügt werden. Die Zeichen- und Wortanzahl werden unter dem Textfeld gezählt und angezeigt. 

## Bild einfügen

Bilder können vom PC Laufwerk eingefügt werden. Das Bild kann in eine Zeile, in einem eigenen Absatz, rechts oder links eingefügt werden. Die Bildgröße muss vor dem Einfügen angepasst werden. 
 
## Sonderelemente

Als Sonderelemente können Sie Sonderzeichen, Formeln, horizontale Linien, Zitate und Tooltips einfügen sowie Bereiche hervorheben. 
Das schmale, nicht umbrechende Sonderzeichen muss zwischen Zahlen und Einheiten verwendet werden. Also zum Beispiel zwischen Zahl und Eurozeichen: 5 €
 
## Tooltip

Wenn Sie einen Verweis für ein Wort einfügen möchten, können Sie einen Tooltip einfügen.  
 
Fügen Sie den entsprechenden erläuternden Text ein und wählen Sie die Tooltip-Position aus. 
 
## Markieren

Wenn die Testteilnehmenden den Text markieren sollen, setzen Sie den Haken bei „Markieren zur Texterschließung erlauben“.
 
## Quellen einfügen

Wenn Quellen eingefügt werden sollen, können Sie dies im Quellenfeld vornehmen. 
 
## Bestätigen/Abbrechen

Wenn Sie mit allen Eingaben zufrieden sind, klicken Sie auf Bestätigen und der Assistent erstellt die Aufgabe im Studio für Sie. Um Ihre Eingaben zu verwerfen, klicken Sie auf Abbrechen. Achtung: In diesem Fall gehen sämtliche Angaben verloren und Sie müssten erneut von vorne beginnen.
