---
lang: de
title: "Eine Studie durchführen mit dem IQB-Testcenter"
---

Dieser Abschnitt erläutert die Funktionen der Webanwendung **IQB-Testcenter** und richtet sich an Verantwortliche, die mit der Vorbereitung, Durchführung und der Auswertung beauftragt sind. Der Begriff **Studie** steht hierbei gleichermaßen für Leistungstests und für Befragungen. Als Voraussetzung muss das **IQB-Testcenter** auf einem Server installiert sein, und ein Super-Admin-Account muss zur Verfügung stehen. Mehr dazu ist dem Kapitel [Einrichtung](/setup/index.qmd) zu entnehmen.

## Schwerpunkte dieses Kapitels:

#### [Vorbereitungen](preparation/index.qmd)

Um eine Studie mit dem **IQB-Testcenter** durchführen zu können, sind einige Vorbereitungen notwendig. Dazu gehören bspw. die Ermittlung von verwendeten Endgeräten, die Studienkonfiguration und einiges mehr.

Schnell zu:

* [Testinhalte](preparation/test-files/index.qmd): Dateien zur Erzeugung von Inhalten und zur Konfiguration eines Tests 
* [System-Check](preparation/system-check/index.qmd): Prüfung zur Eignung der eingesetzen Schulhard- und -software

#### [Durchführung](/study-run/run/index.qmd)

Schnell zu:

* [Gruppenmonitor](run/groupmon/index.qmd)
* [Problemlösung](run/support.qmd)

#### [Studiendaten](/study-run/study-data/index.qmd)

Informationen zur Auswertung sind im separaten Kapitel [Kodieren und Auswerten](/coding/index.qmd) zu finden. Hier wird nur beschrieben, wie die Daten aus dem Testcenter geladen werden können.

#### [Schritt für Schritt](/study-run/step-by-step/index.qmd)

#### [FAQ](/study-run/faq/index.qmd)

## Funktionen des Testcenters

* Anmeldung der Testperson: Über Link (z. B. QR-Code), Name und Kennwort oder zweistufig mit einem zusätzlichen Code
* Anmeldung ohne Personenbezug, z. B. für Befragungen
* Anmeldung im Demo- oder Review-Modus, ohne die Antworten zu speichern
* Mehrere Testhefte: Eine Testperson kann mehrere Testhefte nacheinander bearbeiten mit denselben Anmeldedaten
* zeitliche Beschränkung von Testteilen: Für eine bestimmte Anzahl Aufgaben steht der Testperson eine begrenzte Zeit zur Verfügung
* Fortsetzung erst mit Freigabewort: Die Testdurchführung z. B. in einer Klasse kann synchronisiert werden, indem die Testleitung ein Wort ansagt, mit dem dann der Test fortgesetzt werden kann
* Fortsetzung erst nach vollständiger Präsentation: Um zu vermeiden, dass Teile einer Aufgabe übersehen werden, kann das Weiterblättern solange unterbunden werden, bis alle Audio-Sequenzen abgespielt wurden und alle Seiten vollständig angezeigt wurden
* Fortsetzung erst nach vollständiger Beantwortung
* sofortige Speicherung: Alle Antworten werden sofort zum Server gesendet; nach Abbruch der Testung oder Absturz eines Computers bzw. Browsers kann der vorherige Stand wiederhergestellt werden
* In Abhängigkeit gegebener Antworten und einer zuvor festgelegten Wichtung, kann zu bestimmten Aufgaben verzweigt werden (adaptives Testen)
* Prüfung des Serversystems und der Schulhard- und -software zur Sicherstellung der Durchführbarkeit einer Testung (**System-Check**)
* Steuerung und Beobachtung der Testgruppe durch die Testleitung (**Gruppenmonitor**)

