---
lang: de
title: Kiosk-Mode
---

Es kann bei einer Testdurchführung notwendig sein, die Handhabung eines Gerätes einzuschränken. Dies kann folgende Gründe haben:

* Ablenkung vermeiden: Die Testanwendung nimmt den gesamten Bildschirm ein und man kann nicht versehentlich andere Anwendungen aufrufen, und
* Aussagekraft der Ergebnisse erhöhen durch einheitliche Durchführung: Nur wenn die Schülerinnen und Schüler dieselben Hilfsmittel verwenden, sind die Ergebnisse im Sinne des Testkonstrukts vergleichbar. Wenn Testpersonen z. B. unkontrollierbar eine andere Webseite aufrufen können (Übersetzungsdienst, Kalkulationshilfen), werden andere Fähigkeiten gemessen (latente Variablen) als ursprünglich im Test vorgesehen.

Solch ein beschränkter Zugang zu einem Endgerät, wird auch als **Kiosk-Mode** bezeichnet. Jedes Betriebssystem bietet die Möglichkeit in einen Kiosk-Mode zu wechseln. Die Einstellungen hierfür sind dann proprietär. Eine weitere Möglichkeit unabhängig vom Betriebssystem in einen Kiosk-Mode zu wechseln, bietet der Browser **Safe-Exam-Browser (SEB)**. In diesem Kapitel wird für die Betriebssysteme **Windows** und **IOS** sowohl die Einrichtung des SEB, als auch die Einrichtung des proprietären Kiosk-Modes beschrieben. Mit dem Betriebssystem Android und dem dort verfügbaren Kiosk-Mode, fehlen dem IQB derzeitig noch Erfahrungen, daher findet an dieser Stelle keine Beschreibung dazu statt.

Betriebssystemabhängiger Kiosk-Mode:

* [IOS](../kiosk/ios.qmd)
* [Windows](../kiosk/windows.qmd)

Betriebssystemunabhängiger Kiosk-Mode Safe-Exam-Browser:

* [SEB](../kiosk/seb.qmd)