---
lang: de
title: "Hervorhebungen"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

Hervorhebungen bieten die Möglichkeit, dass Wörter oder Sätze in einem Text hervorgehoben werden. Sie können hervorgehoben werden, wenn eine bestimmte Seite in den Aufgaben erreicht wird (Trigger) oder wenn auf einen Knopf gedrückt wird (Button).

Eine Hervorhebung wird wie im Beispiel violett im Text angezeigt. 

## Hervorhebung anlegen

Zunächst wird die Hervorhebung im Text angelegt. Öffnen Sie dafür den Text und markieren Sie den hervorzuhebenden Textabschnitt. Drücken Sie anschließend auf den Knopf für die Hervorhebung.

Der ausgewählte Bereich ist nun violett eingefärbt – die Hervorhebung ist angelegt.

## Trigger

Um eine automatische Hervorhebung anzuzeigen – das heißt der hervorgehobene Bereich wird angezeigt, sobald die Seite mit der Aufgabe angezeigt wird - muss sich die Aufgabe auf einer separaten Seite befinden.

Legen Sie auf diese Seite in den Abschnitt mit der Aufgabe einen „Auslöser”. Dieser befindet sich in den Elementen im Abschnitt „Sonstige”.

Wählen Sie nun als Aktion „Textabschnitt hervorheben” und unter „Aktionsparameter“ den hervorzuhebenden Bereich.

## Button

Um die Hervorhebung durch einen Knopf zu aktivieren, legen Sie zunächst einen Knopf an. Dafür wird ein Lückentext angelegt, in welchem dann an gewünschter Stelle ein Knopf eingefügt wird. Dieser kann angeklickt werden, um rechts in den Einstellungen bearbeitet zu werden. Die Beschriftung ist dann jener Satz/jenes Wort, dass als Knopf dienen soll.

Als Aktion wird nun „Textabschnitt hervorheben” und als „Aktionsparameter” der hervorzuhebende Bereich ausgewählt.

Damit haben Sie einen Knopf für die Hervorhebung angelegt.