---
lang: de
title: "Verwaltung und Organisation"
---

## Administrative Zugänge

Das Testcenter bietet zwei administrative Ebenen zur Verwaltung und Organisation. 

#### Super-Admin

Nach der Installation des Testcenters ist bereits ein Zugang eingerichtet mit weitgehenden Berechtigungen. Dieser Zugang wird als Super-Admin bezeichnet. Super-Admins können folgendes tun:

* Arbeitsbereiche anlegen
* Nutzer\*innen anlegen (Workspace-Admins) und Zugriffe auf Arbeitsbereiche festlegen
* individuelle Änderungen an Texten (Custom-Text) und Layout des Testcenters vornehmen

Nach der Eingabe der Zugangsdaten ist der Schalter: **Weiter als Admin** zur Anmeldung zu verwenden.

Anschließend werden alle eingerichteten Arbeitsbereiche aufgelistet. Es ist außerdem ein Schalter für die **Systemeinstellungen** zu sehen. Wird dieser Schalter betätigt, wird eine weitere Seite geladen, die die folgenden 3 Reiter anzeigt:

* **Users:**<br>
Hier können bestehende Nutzer\*innen (Workspace-Admins) verwaltet werden. Es können mittels Plus-Schaltfläche neue Nutzer\*innen hinzugefügt werden oder mit der Löschen-Schaltfläche gelöscht werden. Weiterhin stehen zwei Schaltflächen zur Änderungen von Kennwort und Zugriffsebene bereit. Diese beide Schaltflächen sind mit einem Stift-Symbol gekennzeichnet. Ist eine Person als Super-Admin angelegt, wird diese mit einem Stern in der Liste der Nutzer\*innen geführt. Wird in der Liste eine Person markiert, werden auf der rechten Seite alle Arbeitsbereiche angezeigt auf die diese Person Zugriff hat. Die Berechtigung für einen Arbeitsbereich sind noch einmal unterteilt in "read only" (RO) und "read and write" (RW).

* **Arbeitsbereiche:**<br>
Hier werden alle angelegten Bereiche aufgelistet. Es können neue Bereiche angelegt, gelöscht oder nachträglich bearbeitet werden. Durch Markierung eines Bereichs werden rechts alle Personen aufgelistet, die auf diesen Bereich Zugriff haben. Dabei wird noch einmal unterschieden, ob die Personen nur lesend (RO) oder lesend und schreibend (RW) auf den Bereich zugreifen darf. Sollen Personen einen Zugriff auf einen Bereich erhalten, ist der jeweilige Bereich zu markieren und die Person mit RO- oder RW-Zugriff auszuwählen. Anschließend muss zwingend das Speicher-Symbol oben rechts aktiviert werden, ansonsten werden die Änderungen nicht gespeichert.

* **Einstellungen:**<br>
Hier können einige Bereiche des Testcenters an individuelle Bedürfnisse angepasst werden. Es ist bspw. möglich ein Logo einzufügen, die Hintergrundfarbe und Texte der Anwendung zu verändern. Es können auch Textersetzungen für die Bereiche: Testheft, Gruppenmonitor, Login und System-Check erfolgen. Sollen Texte ersetzt werden, ist nach Änderungen zwingend die Speichern-Schaltfläche zu betätigen, um die Änderungen zu übernehmen.


#### Workspace-Admin

Nutzer\*innen, die mit einem solchen Zugang arbeiten, können Daten in Arbeitsbereiche laden und Daten aus einem Bereich herunterladen. Sie haben keinen Zugriff auf andere Stelle des Testcenters. 

::: {.callout-note}
Als Workspace-Admin werden alle eingerichteten Zugänge zum Testcenter bezeichnet, die nicht mit Super-Admin-Rechten ausgestattet sind.
:::

Nach der Eingabe der Zugangsdaten ist der Schalter: **Weiter als Admin** zur Anmeldung zu verwenden.

Anschließend sehen Workspace-Admins alle für sie freigegebenen Arbeitsbereiche. Durch ein Klick auf einen Arbeitsbereich, können Daten in den Arbeitsbereich geladen werden. Falls Antwortdaten vorhanden sind, können diese heruntergeladen werden.

## Zugänge ohne Befugnisse

#### Testpersonen

Dieser Personenkreis erhält die Zugangsdaten durch eine spezielle XML-Datei (XML zur Studien-Definition), die in den Arbeitsbereich der Studie geladen wird. Meldet sich eine Testperson mit den in dieser XML hinterlegten Zugangsdaten am Testcenter an, wird ein Testheft gestartet. Mit anderen Worten, eine Testung wird gestartet.

Nach der Eingabe der Zugangsdaten ist der Schalter: **Weiter** zur Anmeldung zu verwenden.

## Arbeitsbereich

Zur Organisation von Studien stehen Arbeitsbereiche zur Verfügung. Diese legen die Super-Admins an und vergeben die entsprechenden Berechtigungen. Die Benennung dieser Bereiche richtet sich günstigerweise nach dem Zweck der Studie.

Nach der Anmeldung präsentiert das System eine Liste aller Arbeitsbereiche, die für eine Person freigegeben sind. Mit einem Klick auf den jeweiligen Arbeitsbereich wird dieser geöffnet. Zur Liste der Arbeitsbereiche kehrt man zurück, indem man auf das IQB-Logo links oben in der Ecke klickt.

Der Arbeitsbereich hat drei Grundfunktionen. Diese können mit einem Klick auf den entsprechenden Reiter ausgewählt werden:

* Dateien
* System-Check Berichte
* Ergebnisse/Antworten

#### Dateien

Alle Testinhalte und Definitionen eines Tests bzw. einer Befragung (Testdateien), werden über den Reiter: Dateien in das System hochgeladen. 

::: {.callout-note}
Welche Testdateien es gibt und welche Funktionen diese übernehmen ist dem Kapitel: **Daten und Prozesse** zu entnehmen.
:::

Sobald eine Datei hochgeladen ist, ist sie wirksam. D. h. unmittelbar nachdem eine Datei mit Login-Daten (XML zur Studien-Definition) hochgeladen wurde, kann sich eine Testperson mit diesen Daten anmelden. Sollte man feststellen, dass eine Aufgabe Fehler enthält, kann man die Aufgaben-Datei überarbeiten und erneut in das Testcenter laden. Jeder danach gestartete Test, wird dann die neue Aufgabe verwenden.

::: {.callout-note}
Weitere Infos zum Laden von Testdateien sind dem Kapitel: **Daten Upload** zu entnehmen.
:::

#### System-Check Berichte

Hier können die Berichte, die von einem System-Check erzeugt wurden, heruntergeladen werden. Es handelt sich um CSV-Dateien, die man sich gleich z. B. in Microsoft Excel anschauen kann.

#### Ergebnisse/Antworten

Hier können Antworten und Logs, die über die Tests bzw. Befragungen innerhalb dieses Arbeitsbereiches gespeichert wurden, heruntergeladen werden. Auch hier ist das Dateiformat CSV. Sollte das Testcenter über ein Länderportal verwaltet werden, dann steht hier auch ein Download im JSON-Format zur Verfügung.

