---
lang: de
title: "Seiten"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

Jede Aufgabe im Studio besteht aus mindestens einer Seite. Im Editor werden die Seiten untereinander angezeigt. In der Vorschau und im Test kann zwischen den Seiten geblättert oder gescrollt werden. In der Vorstellung können Sie selbst entscheiden, wie zwischen den Seiten gewechselt wird, im Testmodus ist dies allerdings fest eingestellt.

## Seiten anlegen

Für viele Aufgaben ist eine Seite ausreichend. Wenn Sie mehr Seiten hinzufügen möchten, nutzen Sie den „Neue Seite“ Knopf:

Alternativ können Sie auch eine bestehende Seite aufteilen. Dafür muss die Seite aus mehreren Abschnitten bestehen. Wählen Sie den Abschnitt aus, der der erste Abschnitt der neuen Seite sein soll, indem Sie ihn anklicken. Klicken Sie dann auf das „Auftrennen“-Symbol über der aktuellen Seite.

Die Seite wird dann vor dem gewählten Abschnitt aufgetrennt.

Ebenso können Sie Seiten wieder vereinen, indem Sie den „Vereinen“-Knopf anklicken.

## Seiteneinstellungen

Um Seiten anzupassen, klicken Sie auf die drei Punkte in der Leiste über der Seite.

Zwar können Sie die Seitenbreite hier einstellen, es wird aber aus Gründen der einheitlichen Darstellung nicht empfohlen, diese zu ändern. Gleiches gilt für die Randbreite, die die Margen links und rechts für die Seite darstellt.

## Dauerhaft sichtbare Seiten

Die meistgenutzte Einstellung ist die für dauerhaft sichtbare Seiten. Eine dauerhaft sichtbare Seite wird immer angezeigt, während eine andere Seite sichtbar ist. So könnte beispielsweise die dauerhaft sichtbare Seite links einen Stimulus enthalten, während eine oder mehrere Seiten rechts die zu bearbeitenden Items enthalten.




