---
lang: de
title: "Studiendurchführung"
---

::: {.callout-note}
Um Durchführbarkeit und Stabilität einer Studie zu gewährleisten, wird empfohlen vor jeder finalen Studiendurchführung entsprechende Vorbetrachtungen anzustellen. Die Konfiguration der Studie mit Hilfe der Testdateien sollte zudem im Vorfeld gut durchdacht und erprobt sein.
:::

# Testdateien laden

## Arbeitsbereich anlegen

Es muss ein Bereich für die Testdateien der Studie angelegt werden. Dieser sollte einen eindeutigen Namen mit Bezug zur Studie haben. Sobald Testpersonen die Studie gestartet haben, fallen Daten an. Diese Daten können im Arbeitsbereich heruntergeladen werden.

## Aufgaben und Testhefte laden

Im nächsten Schritt werden die XML zur Testheft-Definition und die XML's zur Aufgaben-Definition inkl. aller benötigten Ressourcen (Aufgaben-VOUD, Aufgaben-VOCS, GeoGebra-ITCR und Player-HTML) in den zuvor eingerichteten Arbeitsbereich des Testcenters geladen. Mehr dazu ist im Kapitel: **Daten und Prozesse** zu finden. 

## XML zur Studie-Definition laden

* Testmodus für finale Testung in der XML zur Studien-Definition festlegen (`run-hot-return`oder `run-hot-restart`)
* Zugangsdaten für die Testpersonen in der XML zur Studien-Definition festlegen und falls nötig zeitliche Limits festlegen, ggf. Zeitfenster gut dokumentieren
* XML zur Studiendefinition in den Arbeitsbereich laden
* Einen Probelauf der finalen Version starten und schauen, ob sich alles wie geplant verhält. Es sollte auch geprüft werden, ob entsprechende Daten im Arbeitsbereich erzeugt werden. Wenn alles soweit in Ordnung ist, sollten die erzeugten Daten im Arbeitsbereich gelöscht werden, bevor die finale Studiendurchführung startet. Sonst sind später die Daten des Probelaufs im Datensatz der Studie enthalten.

# Studienlauf

Nun können sich die Testpersonen mit den in der XML zur Studien-Definition festgelegten Zugangsdaten am Testcenter anmelden. Die Anmeldung der Testpersonen erfolgt nach Eingabe der Zugangsdaten mit dem Schalter: **Weiter**. Nach der Anmeldung ist ein sehr reduziertes Startbild zu sehen. Rechts ein paar allgemeine Informationen (Version, Datenschutz etc.), links nur Eingabefelder für Name und Kennwort. Nach der Eingabe wird ein großer Schalter präsentiert, der das Testheft symbolisiert, das gestartet werden soll. Die Anzeige des Testheftes signalisiert auch eine erfolgreiche Anmeldung. Mit Klick auf die Schaltfläche des Testheftes werden alle Testinhalte geladen. Sobald möglich wird auch die erste Seite schon gezeigt und das Laden wird im Hintergrund fortgesetzt.

Die Aufgabennavigation erfolgt rechts oben. Sollte eine Aufgabe aus mehreren Seiten bestehen, dann kann man rechts unten mit entsprechenden Schaltern blättern. Manchmal ist die Bearbeitungszeit begrenzt, dann werden rechtzeitig (5 min und 1 min vor Ende) Hinweise eingeblendet.

Wenn zuvor eingeplant, können die Studienverantwortlichen die Studie auch mittels **Gruppenmonitor** steuern. Mehr dazu ist dem gleichnamigen Kapitel zu entnehmen.

::: {.callout-important}
Während des Studienlaufs fallen permanent Daten an. Diese werden in einem Datensatz im Arbeitsbereich gespeichert. Der Datensatz enthält die gegebenen Antworten und Logs. Dieser Datensatz ermöglicht nach Abschluss der Studie eine Auswertung. Es empfiehlt sich daher in regelmäßigen Abständen diese Daten herunterzuladen und zu sichten. So können schon während des Studienlaufs eventuell bestehende Probleme frühzeitig erkannt werden und nicht erst am Ende der Studie.
:::

# Studie beenden

Die Beantwortung kann jederzeit beendet werden. Die Antworten werden stets sofort gespeichert und es ist hierfür kein Kommando erforderlich. Je nachdem wie die Studie zuvor konfiguriert wurde, kann über ein zusätzliches Aufgabenmenü die Studie beendet werden. Ist dieses Menu nicht eingeschaltet, kann die Studie durch einen Klick auf das IQB-Logo oben links beendet werden. Anschließend gelangt man wieder zur Ansicht der Testhefte. Bei der Beendigung einer Studie kann es je nach Konfiguration der Studie zu Warnungen kommen. Welche Warnungen können je nach Konfiguration angezeigt werden:

**Verlassen eines zeitbeschränkten Blocks:**

Soll die Studie beendet werden und befindet sich die Testperson zu diesem Zeitpunkt in einem zeitbeschränkten Block, wird eine Warnung angezeigt, dass nach Verlassen des Blocks nicht mehr in diesen zurückgekehrt werden kann. Wird diese Warnung bestätigt, wird der Block gesperrt. Haben Testpersonen den Block noch nicht vollständig bearbeitet, ist es nicht mehr möglich die Bearbeitung fortzusetzen.

::: {.callout-important}
Existieren zeitbeschränkte Blöcke in einem Testheft, können diese gesperrt werden, wenn die Studie beendet wird. Eventuell haben Testpersonen noch nicht alle Aufgaben eines Blocks bearbeitet und können nach Beendigung der Studie  nicht mehr auf den Block zugreifen.
:::

**Verlassen bei aktiven Navigationsbeschränkungen:**

Je nach Konfiguration können Aufgaben nur verlassen werden, wenn Pflichtelemente bearbeitet oder alle Bestandteile einer Aufgabe gesehen oder angehört wurden (presentation/ response complete). Befinden sich Personen zum Zeitpunkt der Beendigung in einer solchen Aufgabe und sind die genannten Bedingungen noch nicht erfüllt, kann eine Warnung angezeigt werden. Es sollten dann erst die Bedingungen zum Verlassen der Aufgabe erfüllt werden, bevor die Studie beendet werden kann.

# Studie fortsetzen

Je nach Konfiguration kann das Testheft nach Beendigung der Studie fortgesetzt werden. Auf der Seite der Testheftübersicht ist dann unterhalb des entsprechenden Testheftes der Text: **Fortsetzen** zu sehen. Nach einem Klick auf das Testheft, setzt die Studie an der Stelle fort an der sie beendet wurde. Die zuvor gegebenen Antworten sind vollständig erhalten und einsehbar. Ist das Testheft deaktiviert, ist in der Testheft-Konfiguration eine Sperrung der Studie vorgesehen, wenn diese beendet wird.

::: {.callout-note}
Falls ein Gruppenmonitor zur Steuerung eingesetzt wird, kann auch mittels dieses Monitors die Studie beendet oder fortgesetzt werden. Mehr dazu ist in dem Kapitel **Gruppenmonitor** zu entnehmen.
:::

# Auswertung, Evaluation

Daten wie vorgesehen auswerten, Berichte schreiben, Rückmeldung an Schulen geben. Evaluieren: Dabei hilft die Vorstellung, dass man die gleiche Studie nächste Woche nochmal durchführen soll.