---
lang: de
title: "Markieren mit mehreren Stimuli"
---

Wenn eine Aufgabe ein Markieritem mit einem Stimulus beinhaltet, kann es sinnvoll sein, je einen Stimulus mit dem Markieritem und einen mit den restlichen Aufgaben zu verknüpfen. Dadurch werden Markierungen nicht zur Ablenkung und es können auch mehrere Markieritems für einen Stimulus angelegt werden.

Beispiel: 

![Copyright[^1]](../Grafiken/markieren.mp4)

Diese spezielle Funktion ist nicht zwingend notwendig, wenn es nur ein Markieritem gibt, aber stark empfohlen, wenn es mehr als ein Markieritem gibt oder das Markieren im Text zur Texterschließung als wichtig angesehen wird.

Es gilt: Gelbe Markierungen werden gewertet, blaue und orangene hingegen dienen als Hilfestellung für die Testteilnehmenden.

## Aufgaben anlegen

Um eine Aufgabe wie im Beispiel anzulegen, legen Sie zunächst den Stimulus und die Aufgaben auf verschiedenen Seiten an.

## Markieren

Für jedes Markieritem duplizieren Sie nun den Stimulus, in dem markiert werden soll. Zudem können Sie einen Stimulus mit blauen und orangenen Markierungen anlegen. Das Markieren kann wie gewohnt direkt im Textelement oder separat über Markierelemente ermöglicht werden.

Auf der Stimulusseite sind nun verschiedene Abschnitte mit den verschiedenen Stimuli eingestellt.

## Zustandsvariabel

Vergeben Sie nun eine Zustandsvariable. Nennen Sie diese „Seite” und geben ihr den Wert „1”.

Dies ist gewissermaßen unser Ausgangszustand, den die Schüler*innen als erstes sehen. 

## Sichtbarkeitseinstellung

Nun erhält jeder Stimulus eine Sichtbarkeitseinstellung. Dafür öffnen Sie im gewünschten Abschnitt die Sichtbarkeitseinstellung. Unter „Variablen/Element-ID” kommt der Name der Zustandsvariable, also „Seite”. Jeder Stimulus erhält dann fortlaufend einen der Werte „1”, „2”, „3” ... usw.

Zudem muss „Erneutes Ausblenden erlauben, wenn die Bedingungen nicht mehr erfüllt sind” ausgewählt werden.

Passen Sie dies bei jedem der Stimuli an. Dann werden die Stimuli genau dann angezeigt, wenn die Zustandsvariable den jeweils zugewiesenen Wert annimmt.

## Aufgaben mit Stimuli verknüpfen

Nun müssen die einzelnen Aufgaben mit den Stimuli verknüpft werden, d.h. wenn eine Aufgabe angezeigt wird, soll der zu ihr passende Stimulus angezeigt werden.

Die erste Aufgabe sowie jede Aufgabe, die sich auf diesen ersten Stimulus bezieht, müssen nicht extra mit einem Stimulus verknüpft werden, da sie automatisch zur gleichen Zeit wie der Stimulus der „Seite 1” angezeigt werden.

Die anderen Aufgaben hingegen müssen mit dem jeweils passenden Stimulus verknüpft werden, indem sie mit einem Trigger bzw. Auslöser versehen werden.

Legen Sie einen „Auslöser” an. Dieser befindet sich bei den Elementen im Abschnitt „Sonstige”.

Bei diesem wird nun als Aktion „Zustandsvariable ändern”, als ID „Seite” und als Wert der jeweilige Wert des dazugehörigen Stimulus ausgewählt.

Führen Sie dies für alle Items durch und achten Sie auch darauf, dass alle Items ohne Markierfunktion möglichst mit einem Stimulus ohne gelbe Markierungen verknüpft sind.

[^1]: Copyright Text und Teilaufgaben: IQB e. V., Lizenz: Creative Commons (CC BY). Volltext unter: https://creativecommons.org/licenses/by/4.0/legalcode.de.

    Copyright Grafiken: Pixabay. (2026, 11. Februar). Verkaufsstand [Grafik]. https://pixabay.com/de/illustrations/weihnachtsgesch%C3%A4ft-weihnachten-7621588/, Pixabay. (2026, 11. Februar). Produkte [Grafik]. https://pixabay.com/de/illustrations/hofverkauf-flohmarkt-m%C3%BCll-st%C3%B6bern-5679739/