---
lang: de
title: "Testhefte"
---

Es kann nicht sichergestellt werden, dass die verfügbare Internetverbindung während einer Studiendurchführung stabil und zuverlässig hohe Downloadraten liefert. Es sollte ehr mit dem Gegenteil gerechnet werden. Um unter diesen Voraussetzung eine Studie stabil durchführen zu können, sind die Größen der zu ladenden Testhefte entscheidend. Bereits bei der Aufgabenentwicklung muss daher darauf geachtet werden, die Inhalte so klein wie möglich zu halten. Es kann an dieser Stelle leider keine Angabe zur max. Größe eines Testheftes gemacht werden. Der Grundsatz bei der Aufgabenentwicklung und auch bei der Aufgabenverteilung auf Testhefte, sollte immer lauten: So klein wie möglich. Getreu dieses Grundsatzes, muss die Notwendigkeit audiovisuelle Medien einzusetzen, stets hinterfragt werden und wenn möglich durch Alternativen ersetzt werden. Sind solche Medien unverzichtbar, sollte auf eine ausreichende Komprimierung geachtet werden. Mehr dazu ist dem nachfolgenden Kapitel zu entnehmen. 

### Wie groß ist mein Testheft?

In der Dateiansicht eines Arbeitsbereichs wird die Testheftgröße angezeigt. Um zu verstehen, wie sich diese Größe bildet, müssen die Bestandteile eines Testheftes verstanden werden. Hierfür werden alle Datei unterteilt in:

**Ressourcen:**

Hier werden alle Dateien, die als Ressource für die einzelnen Units benötigt werden, aufgelistet. Ressourcen sind bspw. Player, Pakete (GeoGebra etc.) und Kodierschemen. Die angezeigten Größen in KByte oder Byte entsprechen der tatsächlichen Dateigröße dieser Dateien.

**Units:**

Hier werden die geladenen Units aufgelistet. Die angezeigten Größen neben jeder Unit setzen sich zusammen aus den verwendeten Ressourcen abzgl. des verwendeten Players und der eigentlichen Dateigröße der Unit-XML. Der Player wird an dieser Stelle nicht mit eingerechnet, weil der Player nicht zwingend für die Funktionstüchtigkeit einer Unit erforderlich ist. Er stellt die Unit ja nur dar.

**Testhefte:**

Die angezeigte Größe setzt sich zusammen aus der angezeigten Größe der eingebundenen Units, der Dateigröße der Booklet-XML und dem oder der verwendeten Player. Wichtig zu verstehen ist hierbei, dass der Player immer nur einmal mit eingerechnet wird. Sprich: Befinden sich bspw. 10 Units in einem Testheft und alle Units verwenden den selben Player, wird der Player nicht 10-mal eingerechnet, sondern nur einmal. Verwenden bswp. 5 der 10 Units einen anderen Player, wird die Größe der beiden Player mit eingerechnet.

**Testtaker:**

Die angezeigte Größe ist die Dateigröße der Testtaker-XML.

::: {.callout-tip}
Die Abhängigkeiten zur Größenberechnung können auch mit Hilfe der Browser Entwicklerkonsole detailliert betrachtet werden. Beim Wechsel zur Dateiansicht eines Arbeitsbereichs wird ein HTTP-POST abgesetzt. In der Antwort vom Server ist ein JSON-Objekt zu finden. Dieses listet alle Abhängigkeiten auf.
:::



