---
lang: de
title: "Browser"
---

Darstellung und Verhalten einer Studie sind maßgeblich vom verwendeten Browser abhängig. Es gibt immer wieder die Diskussion darüber, ob ältere Browser bzw. Browserversionen unterstützt werden sollen. Hier wird argumentiert, dass Schulen bzw. deren Träger oft nicht in der Lage seien, die Verwendung aktueller Browser sicherzustellen. Aus dieser Realität ergebe sich, dass die Programmierungen für TBA stets ein Maximum an Abdeckung auch für alte Browser leisten müssten.

Das IQB folgt hier jedoch den Anforderungen an die Datensicherheit, so wie es z. B. das [Bundesamt für Sicherheit in der Informationstechnik](https://www.bsi.bund.de/) formuliert:

> "Der Internet-Browser ist die zentrale Komponente für die Nutzung von Online-Angeboten und stellt somit eins der beliebtesten Ziele für Cyber-Angriffe dar. Hieraus ergibt sich ein besonders hohes Gefahrenpotenzial." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/Der-Browser/der-browser_node.html)

> "Installieren Sie alle Aktualisierungen sofort oder zeitnah nach ihrer Veröffentlichung, sowohl die für Ihren Browser, als auch für alle Erweiterungen und natürlich Ihr Betriebssystem. Verwenden Sie stets die neuste Version Ihres Browsers." [Quelle](https://www.bsi.bund.de/DE/Themen/Verbraucherinnen-und-Verbraucher/Informationen-und-Empfehlungen/Cyber-Sicherheitsempfehlungen/Updates-Browser-Open-Source-Software/updates-browser-open-source-software_node.html)

**Das IQB unterstützt daher nur die jeweils letzten beiden Hauptversionen eines Browsers bzw. die Versionen der letzten 12 Monate.**

Sollten ältere Versionen zum Einsatz kommen, empfiehlt sich eine Voransicht der Aufgaben mit der entsprechenden Browserversion. Hierfür bietet das Testcenter spezielle Modi der Studiendurchführung an, wie bspw. einen Review-Mode. Es kann auch der **System-Check** dafür genutzt werden. Hier können Aufgaben eingebunden werden, die während des System-Checks angezeigt werden. Zum Abschluss des System-Checks können dann Fragen zur Aufgabenansicht gestellt werden. Bspw. könnte gefragt werden, ob ein Audio/Video abgespielt werden konnte. Nach Auswertung des System-Checks, kann dann eine Aussage darüber getroffen werden, ob die Aufgaben mit den verwendeten Browserversionen richtig funktionieren.

::: {.callout-important}
Es gibt abenteuerliche Erweiterungen für Browser (Plugins), die mehr Sicherheit, bessere Performance, weniger Werbung, mehr Privatsphäre usw. versprechen. Oft greifen diese Erweiterungen aber massiv in die Kommunikation des Browsers mit dem Server ein und verfälschen Daten. Bei Problemen sollte man also diese Add-Ons usw. zumindest zeitweise deaktivieren.
:::
