---
lang: de
title: "Video"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

## Videoelemente

Das Medium „Video“ ermöglicht Ihnen, Videodateien ins IQB-Studio zu laden.

Mit einem Klick auf das Element „Video“ der Elementengruppe „Medium“ öffnet sich unmittelbar ein Fenster, in dem Sie die gewünschte Datei auswählen und durch einen Klick auf „Öffnen“ im IQB-Studio hochladen können. Im rechten Reiter „Eigenschaften“ können Sie Anpassungen im Videoelement vornehmen. 

## Anpassen eines Videoelements
 
Neben der Anpassung der ID (z.B.: „video_1“) können Sie mit einem Klick auf den blauen Knopf die Videodatei ändern. Es öffnet sich ein Fenster, in dem Sie die gewünschte Datei auswählen und mit „Öffnen“ ins IQB-Studio laden können.

Nachdem Sie ein Video ins Studio eingefügt haben, können Sie die Breite des Videos begrenzen. Wählen Sie dazu das Video im Editor aus und klicken Sie rechts auf „Maximalbreite setzen“. Anschließend können Sie darunter angeben, wie viele Pixel das Video einnehmen soll.

::: {.callout-tip}
Beachten Sie, dass Seiten im Studio normalerweise auf 750 Pixel Breite begrenzt sind, d.h. Videos sollten höchstens 750 Pixel breit sein, jedoch meistens weniger.
:::