---
lang: de
title: "Audiostimulus Instruktion und Audio getrennt-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

Der Assistent „Stimulus: Audiostimulus – Instruktion und Hörtext getrennt“ hilft Ihnen beim Erstellen von Audiostimuli mit getrennten Instruktionsaudios.

Im Assistenten wählen Sie die Medienquellen für das Instruktions- und Stimulusaudio aus. Anschließend geben Sie die Quelle an. Dabei können Sie zwischen den Sprachen Deutsch, Englisch und Französisch wählen. Zuletzt geben Sie die Situierung, Fragestellung sowie mögliche Hinweise ein.

## Instruktions- und Stimulusaudios

Klicken Sie auf den blauen Kreis „Medienquelle ändern“. Anschließend öffnet sich ein Auswahlmenü und Sie können eine eigene Audiodatei auswählen. Auf der rechten Seite können Sie die Abspielhäufigkeit auswählen.

::: {.callout-note}
Sollte die Einstellung mehr als 1 betragen, wird innerhalb des Audioelements eine Anzeige mit der bisherigen Anzahl der Audiostarts im Verhältnis zu den maximal verfügbaren Audiostarts generiert.
:::

## Quelle

Die Quelle wird im Texteditor des Studios verfasst. Weitere Details dazu finden Sie hier: [Editor](../../Medienelemente/Text/index.qmd)

## Sprache 

Sie können zwischen Deutsch, Französisch und Englisch wählen.

## Situierung, Frage, Operator, Hinweise, o.Ä.

Die Situierung wird im Texteditor des Studios verfasst. Weitere Details dazu finden Sie hier: [Editor](../../Medienelemente/Text/index.qmd)

## Bestätigen/Abbrechen

Wenn Sie mit allen Eingaben zufrieden sind, klicken Sie auf „Bestätigen“ und der Assistent erstellt die Aufgabe im Studio für Sie. Um Ihre Eingaben zu verwerfen, klicken Sie auf Abbrechen. Achtung: In diesem Fall gehen sämtliche Angaben verloren und Sie müssten erneut von vorne beginnen. 

::: {.callout-note}
Der bei der Aufgabenerstellung automatisch generierte Text „Drücke zuerst auf das Dreieck, dann startet das Audio.“ kann nachträglich in den Texteigenschaften angepasst werden. 
:::

::: {.callout-note}
Der Aufforderungstext „Bitte starten.“ inklusive roter Umrahmung des jeweiligen Audios erscheint automatisch, sofern das Audio fünf Sekunden nach Betreten der Seite nicht gestartet wurde. Diese Einstellung kann nur im erweiterten Modus angepasst werden.  
:::
