---
lang: de
title: "Rechenkästchen-Assistent"
---

::: {.callout-caution}
Diese Seite wird zurzeit überarbeitet. Weitere Inhalte und Grafiken folgen demnächst.
:::

# Rechenkästchen 

Der Assistent „Rechenkästchen“ hilft Ihnen beim Erstellen von schriftlichen Rechenaufgaben (Addition, Subtraktion und Multiplikation mit mehrstelligen Zahlen). 

## Beispiel:
 
Im Assistenten wählen Sie die Rechenart aus und geben die Termzeilen ein.

## Rechenart
 
Bei der Rechenart können Sie zwischen Addition, Subtraktion sowie Multiplikation mit mehrstelligen Zahlen wählen. 

::: {.callout-note}
Ein Tooltipp wird nur bei Subtraktionsaufgaben eingeblendet. 
:::

## Termzeilen
 
Um einen Term einzutragen, klicken Sie in das jeweilige Feld. Mit einem Klick auf das Plus können Sie weitere Termzeilen hinzugefügen. Weitere Termzeilen können nur für Additions- und Subtraktionsaufgaben hinzugefügt werden. Möchten Sie eine Termzeile wieder entfernen, klicken Sie auf das Kreuz an der rechten Seite.

## Bestätigen/Abbrechen

Wenn Sie mit allen Eingaben zufrieden sind klicken Sie auf „Bestätigen“ und der Assistent erstellt die Aufgabe im Studio für Sie. Um Ihre Eingaben zu verwerfen klicken Sie auf „Abbrechen“. Achtung: In diesem Fall gehen sämtliche Angaben verloren und Sie müssten erneut von vorne beginnen.