---
lang: de
---

Hier finden Sie eine Einführung zur älteren Anwendung **Teststudio** und eine Einführung zur aktuellen Anwendung **Studio**. In der Einführung zum **Studio** finden Sie auch Videos die nicht nur etwas mit dem **Studio** zu tun haben, sondern auch Videos zum Editor usw..

# Einführung Teststudio

**Inhalt:**

* Struktur, Aufbau und Funktionen des Teststudios<br>
* Aufbau und Funktion des integrierten Editors

**Format:**

* 4:3
* UT: nein
* Inhaltsverzeichnis: nein
* Kategorie: Einführung
* Sprache: Deutsch
* techn. Niveau: mittel
* Dauer: 19:27 [min]:[s]

**Stand:**

Juli 2020

**Link:**

[HU-Box](https://box.hu-berlin.de/f/e29f3e8d8c35480f8531/)

---

# Einführung Studio

**Inhalt:**

* Struktur, Aufbau und Funktionen des Studios
* Aufbau und Funktion des integrierten Editors, Kodierung und Kommentare

**Format:**

* 4:3
* UT: nein
* Inhaltsverzeichnis: nein
* Kategorie: Einführung
* Sprache: Deutsch
* techn. Niveau: niedrig

**Stand:**

September 2022

**Link:**

[HU-Moodle](https://moodle.hu-berlin.de/course/view.php?id=114701#section-0)