---
lang: de
---

# Instrumente

**Inhalt:**

Vorführung der TBA Testsysteme (Teststudio und Testcenter) und deren Zusammenwirken

**Format:**

* 4:3
* UT: nein
* Inhaltsverzeichnis: nein
* Kategorie: Einführung
* Sprache: Deutsch
* techn. Niveau: niedrig
* Dauer: 11:14 [min]:[s]

**Stand:**

Mai 2021

**Link:**

[HU-Box](https://box.hu-berlin.de/f/07de21dff3c948d2bff4/)

---

# Vom Entwurf zur Testdurchführung

**Inhalt:**

Einführung IQB TBA-Systeme

Teil 1:

* Aufgabenentwurf mit dem Teststudio

Teil 2:

* Bearbeitung der erzeugten Testdateien

Teil 3:

* Erprobung eines Testdurchlaufs mit dem Testcenter
* Nachbearbeiten der Testdateien

Teil 4:

* Finale Testdurchführung mit dem Testcenter
* Auswertung des Tests
* Durchführung System-Check
* Zuschalten Testleitungskonsole

**Format:**

* 16:9
* UT: ja
* Inhaltsverzeichnis: ja
* Kategorie: Schulung
* Sprache: Deutsch
* techn. Niveau: mittel
* Dauer Teil1: 15:37 [min]:[s]
* Dauer Teil2: 29:21 [min]:[s]
* Dauer Teil3: 33:30 [min]:[s]
* Dauer Teil4: in Vorbereitung

**Stand:**

September 2021

**Link:**

[HU-Moodle](https://moodle.hu-berlin.de/course/view.php?id=107279)